import fs from 'node:fs';
import {build} from 'esbuild';
const bundle=await build({stdin:{contents:`import {roadPoints} from './src/world/city/geometry'; export {roadPoints};`,resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});
const {roadPoints}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const v3=JSON.parse(fs.readFileSync('src/world/city/maps/city-main.json','utf8')),v2=JSON.parse(fs.readFileSync('artifacts/city-main-v3/v2-base.json','utf8'));
const hubs=['central','east','north','west','south'];
function rampMetrics(map,id){const roads=map.roads.filter(r=>r.groupId==='system-'+id&&r.gore),pts=roads.flatMap(roadPoints);return {width:Math.max(...pts.map(p=>p.x))-Math.min(...pts.map(p=>p.x)),depth:Math.max(...pts.map(p=>p.z))-Math.min(...pts.map(p=>p.z)),minY:Math.min(...pts.map(p=>p.y??0)),maxY:Math.max(...pts.map(p=>p.y??0))};}
function radius(road){const pts=roadPoints(road);let min=Infinity;for(let i=1;i+1<pts.length;i++){const a=pts[i-1],b=pts[i],c=pts[i+1],ab=Math.hypot(b.x-a.x,b.z-a.z),bc=Math.hypot(c.x-b.x,c.z-b.z),ac=Math.hypot(c.x-a.x,c.z-a.z),cross=Math.abs((b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x));if(cross>1e-6)min=Math.min(min,ab*bc*ac/(2*cross));}return min;}
const result={roads:v3.roads.length,intersections:v3.intersections.length,objects:v3.objects.length,signs:v3.signs.length,names:Object.keys(v3.roadNames).length,hubs:hubs.map(id=>{const before=rampMetrics(v2,id),after=rampMetrics(v3,id);return{id,before,after,areaReduction:1-after.width*after.depth/(before.width*before.depth),radii:v3.roads.filter(r=>r.groupId==='system-'+id&&r.gore&&!r.id.endsWith('right')).map(r=>({id:r.id,radius:radius(r)}))};}),signTypes:Object.fromEntries([...new Set(v3.signs.map(s=>s.type))].map(type=>[type,v3.signs.filter(s=>s.type===type).length])),signTemplates:Object.fromEntries([...new Set(v3.signs.map(s=>s.template))].map(type=>[type,v3.signs.filter(s=>s.template===type).length])),props:Object.fromEntries([...new Set(v3.objects.map(s=>s.prefabId))].map(type=>[type,v3.objects.filter(s=>s.prefabId===type).length])),metadata:v3.environment.metadata};
fs.writeFileSync('artifacts/city-main-v3/metrics.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
