import {
  cloneVehiclePhysicsConfig,
  DEFAULT_VEHICLE_PHYSICS_CONFIG,
} from './defaultVehiclePhysicsConfig';
import type { VehiclePhysicsConfig } from './VehiclePhysicsConfig';
import { SPORT_COUPE_DIMENSIONS } from '../VehicleDimensions';

const degreesToRadians = (degrees: number): number => (degrees * Math.PI) / 180;

/**
 * A quick but approachable rear-wheel-drive grand-touring coupe.
 *
 * Peak output is roughly 270 kW around 6,500 rpm.  The broad torque curve,
 * progressive throttle and close-ratio seven-speed make it clearly quicker
 * than the family sedan without giving keyboard users an on/off supercar.
 */
export const SPORTS_COUPE_PHYSICS_CONFIG: VehiclePhysicsConfig = {
  ...DEFAULT_VEHICLE_PHYSICS_CONFIG,
  ...SPORT_COUPE_DIMENSIONS,
  mass: 1_490,
  trackWidth: 1.61,
  frontWeightBias: 0.52,
  centerOfMassHeight: 0.46,
  centerOfMassLongitudinalOffset: -0.03,
  yawInertia: 2_360,
  drivetrainType: 'RWD',
  frontTorqueSplit: 0,
  rearTorqueSplit: 1,
  drivetrainLayout: 'RWD',
  drivenWheelWeightFraction: 0.48,
  engine: {
    ...DEFAULT_VEHICLE_PHYSICS_CONFIG.engine,
    partThrottleExponent: 1.05,
    revHang: { enabled: true, holdTime: 0.045, decayTime: 0.14, strength: 0.34 },
    idleRPM: 920,
    stallRPM: 560,
    idleControlMaxTorque: 74,
    idleControlBandRPM: 290,
    idleControlStrength: 74,
    shiftRecommendation: {
      lightLoadRPM: 2_050,
      highLoadRPM: 3_350,
      throttleCurveExponent: 0.72,
      firstGearOffsetRPM: 180,
      minimumSpeedKmh: 10,
      hysteresisRPM: 180,
    },
    redlineWarningRPM: 7_050,
    redlineRPM: 7_350,
    revLimiterRPM: 7_350,
    revLimiterType: 'soft',
    maxRPM: 7_600,
    engineInertia: 0.31,
    engineFrictionTorque: 18,
    engineBrakingStrength: 82,
    engineBraking: 100,
    throttleResponseRate: 3.75,
    throttleResponse: 3.75,
    throttleReleaseResponse: 8.5,
    starterTorque: 145,
    torqueCurve: [
      { rpm: 920, torque: 178 },
      { rpm: 1_500, torque: 270 },
      { rpm: 2_500, torque: 348 },
      { rpm: 3_500, torque: 390 },
      { rpm: 4_500, torque: 410 },
      { rpm: 5_500, torque: 405 },
      { rpm: 6_500, torque: 395 },
      { rpm: 7_050, torque: 360 },
      { rpm: 7_350, torque: 310 },
      { rpm: 7_600, torque: 220 },
    ],
  },
  transmission: {
    drivetrainLash: { reversalTime: 0.07, torqueDeadzone: 8 },
    reverseRatio: -3.44,
    gearRatios: {
      1: 3.77,
      2: 2.26,
      3: 1.65,
      4: 1.29,
      5: 1.03,
      6: 0.84,
      7: 0.68,
    },
    finalDrive: 3.46,
    finalDriveRatio: 3.46,
    efficiency: 0.92,
    drivetrainEfficiency: 0.92,
    shiftTime: 0.095,
    reverseLockoutSpeed: 1.5,
    minimumClutchDisengagementForShift: 0.88,
    synchroStrength: 1,
  },
  clutch: {
    ...DEFAULT_VEHICLE_PHYSICS_CONFIG.clutch,
    maxClutchTorque: 610,
    maxTorque: 610,
    engagementCurveExponent: 1.72,
    torqueCapacityExponent: 1.58,
    couplingStiffness: 13.2,
    disengagementRate: 8.5,
    engagementRate: 2.35,
  },
  autoClutch: {
    ...DEFAULT_VEHICLE_PHYSICS_CONFIG.autoClutch,
    gearChangeDelay: 0.095,
    launchFullyEngagedSpeed: 5.8,
    launchMinimumEngagement: 0.14,
    antiStallRPMFraction: 0.7,
    takeoverRate: 1.55,
  },
  brakes: {
    pedalCurveExponent: 1.05,
    applyResponse: 14,
    releaseResponse: 20,
    maxBrakeTorqueFront: 3_180,
    maxBrakeTorqueRear: 1_560,
    frontBrakeBias: 0.67,
    maxBrakeForce: 14_150,
    handbrakeTorque: 2_680,
    handbrakeAxle: 'rear',
    maxHandbrakeForce: 8_000,
    response: 14,
    handbrakeResponse: 20,
  },
  steering: {
    maxRoadWheelAngle: degreesToRadians(30),
    maxSteeringAngle: degreesToRadians(30),
    steeringWheelLock: degreesToRadians(780),
    steeringRatio: 13,
    steeringResponse: 3.55,
    steeringReturnRate: 6.2,
    steeringDamping: 12.5,
    highSpeedSteeringReduction: 0.0032,
    highSpeedReduction: 0.0032,
    highSpeedReferenceSpeed: 17.68,
    highSpeedMinimumAuthority: 0.2,
    ackermannFactor: 0.91,
    yawResponseScale: 0.47,
    minimumYawResponseRate: 1.9,
    maximumYawResponseRate: 8.2,
    handbrakeOversteerGain: 1.38,
    maximumYawRate: 1.5,
  },
  aero: {
    dragCoefficient: 0.31,
    frontalArea: 2.04,
    airDensity: 1.225,
    liftCoefficientFront: -0.02,
    liftCoefficientRear: -0.05,
  },
  tires: {
    loadSensitivity: 0.06,
    wheelInertia: 1.45,
    rollingResistance: 0.013,
    longitudinalGrip: 1.04,
    lateralGrip: 1.08,
    gripCoefficient: 1.04,
    corneringStiffnessFront: 87_000,
    corneringStiffnessRear: 91_000,
    lateralSlipRecoveryRate: 9.2,
    handbrakeRearGripFactor: 0.1,
    maximumBodySlipAngle: degreesToRadians(42),
    combinedGripLateralReduction: 0.26,
    contactYawInfluence: 0.6,
    peakSlipRatio: 0.1,
    peakSlipAngle: degreesToRadians(7.5),
    gripFalloff: 0.31,
  },
  suspension: {
    rideHeight: 0.115,
    restLength: 0.3,
    springRateFront: 39_000,
    springRateRear: 41_000,
    damperCompressionFront: 2_850,
    damperCompressionRear: 2_950,
    damperReboundFront: 4_250,
    damperReboundRear: 4_400,
    suspensionTravel: 0.105,
    bumpStopStartRatio: 0.8,
    bumpStopStiffness: 240_000,
    antiRollStiffnessFront: 14_000,
    antiRollStiffnessRear: 13_000,
    antiRollStiffness: 27_000,
  },
  driverAids: {
    ...DEFAULT_VEHICLE_PHYSICS_CONFIG.driverAids,
    antiStallStrength: 0.62,
    absEnabled: false,
    tractionControlEnabled: false,
    stabilityControlEnabled: true,
  },
  safety: {
    ...DEFAULT_VEHICLE_PHYSICS_CONFIG.safety,
    maxForwardSpeed: 105,
    maxReverseSpeed: 28,
  },
};

export function createSportsCoupePhysicsConfig(): VehiclePhysicsConfig {
  return cloneVehiclePhysicsConfig(SPORTS_COUPE_PHYSICS_CONFIG);
}
