import type { VehicleControlMode, VehicleInputState } from '../../input/VehicleInputState';
import {
  createDefaultVehiclePhysicsConfig,
  type Gear,
  type DriveSelector,
  type VehiclePhysicsConfig,
  type VehicleChassisConfig,
} from '../config';
import { BrakeSystem } from './BrakeSystem';
import { DriverAssistSystem, type DriverAssistOptions, type DriverAssistSnapshot } from './DriverAssistSystem';
import { SteeringSystem } from './SteeringSystem';
import { WHEEL_IDS, type WheelContactSet, type WheelId } from './WheelContact';
import { wheelLocalPosition } from '../VehicleDimensions';
import { SuspensionSystem } from './SuspensionSystem';
import { WheelRotationSystem } from './WheelRotationSystem';
import type { Differential, DifferentialSnapshot } from './Differential';
import { createDifferential } from './LimitedSlipDifferential';
import { resolveVehicleCapabilities, type VehicleCapabilities } from '../VehicleCapabilities';
import type { DriveTorqueSource } from './DriveTorqueSource';
import { ElectronicParkingBrake, type ParkingBrakeSnapshot } from '../control/ElectronicParkingBrake';
import { AutoHoldController, type AutoHoldSnapshot } from '../control/AutoHoldController';
import { AWDTorqueDistribution, type AWDTorqueDistributionSnapshot } from './AWDTorqueDistribution';
import type { ChassisPhysicsState, WheelPhysicsState, WheelPhysicsStateSet } from './WheelPhysicsState';
import { clamp, clamp01, wrapAngle } from './math';
import { ICEPowertrain } from '../powertrain/ICEPowertrain';
import type { Powertrain, PowertrainSnapshot, PowertrainInitialState, PowertrainUpdateContext, ICEVehicleTelemetry, PowertrainTransmissionSnapshot, ShiftRejectionReason } from '../powertrain/Powertrain';
import { validateVehiclePlatformConfig } from '../config/validateVehiclePlatformConfig';
import type { TransmissionSnapshot } from '../transmission/TransmissionSystem';

export interface VehicleWorldBounds {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
}

/** Per-step road information supplied by the world/track system. */
export interface VehicleEnvironment {
  /** Four independently queried tyre contacts; material coefficients are relative to asphalt. */
  wheelContacts?: WheelContactSet;
  /** Upward unit surface normal. Wheel-contact normals take priority when present. */
  groundNormal?: { x: number; y: number; z: number };
  /** Positive means uphill in the vehicle's local forward direction. */
  gradeRadians?: number;
  /** Multiplier for wet, gravel, etc. One is the configured dry-road grip. */
  surfaceGripMultiplier?: number;
  /** Optional axle-independent overrides layered on top of surfaceGripMultiplier. */
  surfaceLongitudinalGripMultiplier?: number;
  surfaceLateralGripMultiplier?: number;
  rollingResistanceMultiplier?: number;
  /** Wind/collisions may inject a signed force without entering the drivetrain. */
  externalLongitudinalForce?: number;
  bounds?: VehicleWorldBounds;
}

/** Pose/velocity returned by the separate, planar static collision resolver. */
export interface VehicleContactCorrection {
  x: number;
  z: number;
  velocityX: number;
  velocityZ: number;
  yawRate?: number;
}

interface TyreContactForces {
  staticSupported: boolean;
  wheelForce: number;
  powertrainForce: number;
  serviceBrakeForce: number;
  handbrakeForce: number;
  rollingForce: number;
  rollingMagnitude: number;
  longitudinalForceLimit: number;
  frontLateralGrip: number;
  rearLateralGrip: number;
  frontLongitudinalUsage: number;
  rearLongitudinalUsage: number;
  contactYawAcceleration: number;
  lateralForce: number;
  yawMoment: number;
  lateralForceLimit: number;
}

type FourWheelValues = [number, number, number, number];

export interface VehicleInitialState {
  vehicleOperational?: boolean;
  driveAvailable?: boolean;
  shaftAngularVelocity?: number;
  currentFuelL?: number;
  x?: number;
  z?: number;
  yaw?: number;
  speed?: number;
  gear?: Gear;
  engineRPM?: number;
  /** Defaults to true; false creates a stopped/stalled engine at zero rpm. */
  engineRunning?: boolean;
  clutchEngagement?: number;
  controlMode?: VehicleControlMode;
  driveSelector?: DriveSelector;
}

export type { ShiftRejectionReason } from '../powertrain/Powertrain';

/** Result lets the UI distinguish a successful stop from a blocked restart. */
export type EngineToggleResult = 'started' | 'stopped' | 'start-rejected';

export interface VehicleForceSnapshot {
  /** Signed tyre force generated by the powertrain, including back-drive. */
  wheelForce: number;
  /** Combined applied service-brake and handbrake force. */
  brakeForce: number;
  serviceBrakeForce: number;
  handbrakeForce: number;
  aerodynamicDragForce: number;
  rollingResistanceForce: number;
  gradeForce: number;
  externalForce: number;
  netForce: number;
  /** Signed subset of wheelForce that opposes motion with the throttle shut. */
  engineBrakingForce: number;
  /** Torque crossing the clutch; exposed for slip/capacity diagnostics. */
  clutchTorque: number;
  clutchSlipAngularVelocity: number;
}

export interface VehicleSnapshot extends ICEVehicleTelemetry {
  powertrain: PowertrainSnapshot;
  vehicleOperational: boolean;
  driveAvailable: boolean;
  baseVehicleMass: number;
  effectiveVehicleMass: number;
  driveMode?: import('../config').VehicleDriveMode;
  x: number;
  z: number;
  yaw: number;
  speed: number;
  speedKmh: number;
  acceleration: number;
  yawRate: number;
  /** Velocity direction relative to the body; positive points toward vehicle-right. */
  bodySlipAngle: number;
  /** Signed body-local lateral velocity, in m/s. */
  lateralVelocity: number;
  /** Signed body-local lateral acceleration; positive is vehicle-right. */
  lateralAcceleration: number;
  /** Remaining rear lateral authority after parking-brake lockup. */
  rearLateralGripFactor: number;
  throttle: number;
  brake: number;
  handbrake: number;
  steer: number;
  controlMode: VehicleControlMode;
  /** State of the most recent shift event; compare sequence for a new event. */
  shiftRejected: boolean;
  shiftRejectionReason: ShiftRejectionReason | null;
  shiftEventSequence: number;
  steeringAngle: number;
  /** Individual visual/diagnostic road-wheel angles after Ackermann correction. */
  leftRoadWheelAngle: number;
  rightRoadWheelAngle: number;
  steeringWheelAngle: number;
  forces: VehicleForceSnapshot;
  wheels: WheelPhysicsStateSet;
  chassis: ChassisPhysicsState;
  transmission: TransmissionSnapshot;
  parkingBrake: ParkingBrakeSnapshot;
  autoHold: AutoHoldSnapshot;
  electronicDifferentialActive: boolean;
  differential: DifferentialSnapshot;
  rearDifferential?: DifferentialSnapshot;
  awd?: AWDTorqueDistributionSnapshot;
  driverAssists: DriverAssistSnapshot;
  /** True for the update in which corrupt numeric state was restored. */
  recoveredFromInvalidState: boolean;
}

interface ValidCoreState {
  powertrain: PowertrainInitialState;
  x: number;
  z: number;
  yaw: number;
  speed: number;
  controlMode: VehicleControlMode;
  bodySlipAngle: number;
  lateralVelocity: number;
  contactSlipRecovery: boolean;
  contactSlipHoldTime: number;
  yawRate: number;
}

const ZERO_FORCES: VehicleForceSnapshot = {
  wheelForce: 0,
  brakeForce: 0,
  serviceBrakeForce: 0,
  handbrakeForce: 0,
  aerodynamicDragForce: 0,
  rollingResistanceForce: 0,
  gradeForce: 0,
  externalForce: 0,
  netForce: 0,
  engineBrakingForce: 0,
  clutchTorque: 0,
  clutchSlipAngularVelocity: 0,
};

/**
 * Four independent supported wheel contacts and a planar chassis. This class
 * consumes only the normalized VehicleInputState contract. It has no knowledge
 * of keyboards, gamepads, steering wheels, renderers, or wall-clock time.
 */
type ICEAccess<P extends Powertrain, K extends keyof ICEPowertrain> = P extends ICEPowertrain ? ICEPowertrain[K] : ICEPowertrain[K] | undefined;
type DynamicsConfig<P extends Powertrain> = P extends ICEPowertrain ? VehiclePhysicsConfig : VehicleChassisConfig;
export type VehicleSnapshotFor<P extends Powertrain> = P extends ICEPowertrain ? VehicleSnapshot :
  Omit<VehicleSnapshot, keyof ICEVehicleTelemetry | 'transmission'> & { gear: Gear | null; transmission: PowertrainTransmissionSnapshot };

export class VehicleDynamics<TPowertrain extends Powertrain = ICEPowertrain> {
  public readonly powertrain: TPowertrain;
  private get icePowertrain(): ICEPowertrain | undefined { return this.powertrain instanceof ICEPowertrain ? this.powertrain : undefined; }

  public get fuel(): ICEAccess<TPowertrain, 'fuel'> { return this.icePowertrain?.fuel as ICEAccess<TPowertrain, 'fuel'>; }
  public get engine(): ICEAccess<TPowertrain, 'engine'> { return this.icePowertrain?.engine as ICEAccess<TPowertrain, 'engine'>; }
  public get clutch(): ICEAccess<TPowertrain, 'clutch'> { return this.icePowertrain?.clutch as ICEAccess<TPowertrain, 'clutch'>; }
  public get autoClutch(): ICEAccess<TPowertrain, 'autoClutch'> { return this.icePowertrain?.autoClutch as ICEAccess<TPowertrain, 'autoClutch'>; }
  public get gearbox(): ICEAccess<TPowertrain, 'gearbox'> { return this.icePowertrain?.gearbox as ICEAccess<TPowertrain, 'gearbox'>; }
  public get upshiftAdvisor(): ICEAccess<TPowertrain, 'upshiftAdvisor'> { return this.icePowertrain?.upshiftAdvisor as ICEAccess<TPowertrain, 'upshiftAdvisor'>; }
  public get drivetrainLash(): ICEAccess<TPowertrain, 'drivetrainLash'> { return this.icePowertrain?.drivetrainLash as ICEAccess<TPowertrain, 'drivetrainLash'>; }
  /** Shared mass entry for all mass-dependent physics; config.mass stays base mass. */
  private readonly runtimeConfig: VehicleChassisConfig;
  public get effectiveVehicleMass(): number { return this.runtimeConfig.mass; }

  public setCurrentFuelL(litres: number): void {
    this.icePowertrain?.setCurrentFuelL(litres);
    this.synchronizePowertrainMass();
  }

  private synchronizePowertrainMass(): void {
    this.runtimeConfig.mass = this.config.mass + this.powertrain.variableMassKg;
  }
  public readonly capabilities: VehicleCapabilities;
  public get torqueSource(): DriveTorqueSource { return this.powertrain.torqueSource; }
  public readonly parkingBrake: ElectronicParkingBrake | undefined;
  public readonly autoHold: AutoHoldController | undefined;
  public setAutoHoldEnabled(enabled: boolean): void { this.autoHold?.setEnabled(enabled); }
  public readonly brakes: BrakeSystem;
  public readonly driverAssists: DriverAssistSystem;
  public setDriverAssistOptions(options: DriverAssistOptions): void { this.driverAssists.setOptions(options); }
  public readonly steering: SteeringSystem;
  public readonly suspension: SuspensionSystem;
  public readonly wheelRotation: WheelRotationSystem;
  public readonly differential: Differential;
  public readonly rearDifferential: Differential | undefined;
  public readonly awd: AWDTorqueDistribution | undefined;
  public get transmission(): TPowertrain['transmission'] { return this.powertrain.transmission; }

  public x = 0;
  public z = 0;
  public yaw = 0;
  /** Signed longitudinal velocity in m/s; negative means reversing. */
  public speed = 0;
  public acceleration = 0;
  public yawRate = 0;
  /** Positive means the velocity vector points to the vehicle's right. */
  public bodySlipAngle = 0;
  public lateralVelocity = 0;
  public lateralAcceleration = 0;
  public rearLateralGripFactor = 1;

  private readonly powertrainContext: PowertrainUpdateContext = {
    dt: 0, throttle: 0, brake: 0, vehicleSpeed: 0, vehicleLateralSpeed: 0,
    drivenWheelAngularVelocity: 0, torqueLimitFactor: 1, clutchPedal: 1,
  };
  private forces: VehicleForceSnapshot = { ...ZERO_FORCES };
  private previousShiftUp = false;
  private previousShiftDown = false;
  private controlMode: VehicleControlMode = 'normal';
  private shiftRejected = false;
  private shiftRejectionReason: ShiftRejectionReason | null = null;
  private shiftEventSequence = 0;
  private lastValidState: ValidCoreState;
  private recoveredThisUpdate = false;
  private wheels = {} as Record<WheelId, WheelPhysicsState>;
  private readonly escLateralLimits = [0, 0, 0, 0];
  /** Preserve an oblique collision's tangent velocity while contact settles. */
  public driveMode: import('../config').VehicleDriveMode | undefined;
  private driveModeThrottleExponent = 1;
  private contactSlipRecovery = false;
  private contactSlipHoldTime = 0;

  public constructor(
    public readonly config: DynamicsConfig<TPowertrain> = createDefaultVehiclePhysicsConfig() as DynamicsConfig<TPowertrain>,
    initialState: VehicleInitialState = {},
    injectedPowertrain?: TPowertrain,
  ) {
    validateVehiclePlatformConfig(config);
    if (injectedPowertrain === undefined && !('engine' in config)) throw new Error('A non-ICE chassis requires a Powertrain');
    this.powertrain = injectedPowertrain ?? (new ICEPowertrain(config as VehiclePhysicsConfig) as unknown as TPowertrain);
    if (config.transmission && (config.transmission.type ?? 'MANUAL') !== this.powertrain.transmission.type) throw new Error('Powertrain transmission disagrees with config');
    if (this.powertrain.supportsManualSelection && this.powertrain.transmission.type !== 'TORQUE_CONVERTER_AT' && this.powertrain.transmission.type !== 'DCT') throw new Error('Manual selection requires stepped AT/DCT');
    if (config.transmission && (config.transmission.supportsManualSelection === true) !== this.powertrain.supportsManualSelection) throw new Error('Powertrain manual selection disagrees with config');
    if (config.autoHold && this.powertrain.transmission.type === 'MANUAL') throw new Error('Auto Hold requires a selector-based Powertrain');
    this.capabilities = resolveVehicleCapabilities(config, undefined, this.powertrain);
    this.parkingBrake = this.capabilities.electronicParkingBrake && config.parkingBrake
      ? new ElectronicParkingBrake(config.parkingBrake) : undefined;
    this.autoHold = this.capabilities.autoHold && config.autoHold && this.powertrain.transmission.type !== 'MANUAL'
      ? new AutoHoldController(config.autoHold) : undefined;
    this.runtimeConfig = { ...config, mass: config.mass + this.powertrain.variableMassKg };
    const axle = config.drivetrainType === 'RWD' ? 'rear' : 'front';
    this.differential = createDifferential(axle, axle === 'rear' ? config.rearDiff : config.frontDiff);
    this.rearDifferential = this.capabilities.awd ? createDifferential('rear', config.rearDiff) : undefined;
    this.awd = this.capabilities.awd ? new AWDTorqueDistribution(config) : undefined;
    this.brakes = new BrakeSystem(config.brakes, config.wheelRadius);
    this.driverAssists = new DriverAssistSystem(this.runtimeConfig);
    this.steering = new SteeringSystem(
      config.steering,
      config.wheelBase,
      config.frontTrackWidth,
    );
    this.suspension = new SuspensionSystem(this.runtimeConfig);
    this.wheelRotation = new WheelRotationSystem(config.tires, config.wheelRadius);
    this.lastValidState = {
      powertrain: {},
      x: 0,
      z: 0,
      yaw: 0,
      speed: 0,
      controlMode: 'normal',
      bodySlipAngle: 0,
      lateralVelocity: 0,
      contactSlipRecovery: false,
      contactSlipHoldTime: 0,
      yawRate: 0,
    };
    this.reset(initialState);
  }

  public reset(initialState: VehicleInitialState = {}): VehicleSnapshotFor<TPowertrain> {
    this.powertrain.reset({ vehicleOperational: initialState.vehicleOperational, driveAvailable: initialState.driveAvailable,
      shaftAngularVelocity: initialState.shaftAngularVelocity, gear: initialState.gear, driveSelector: initialState.driveSelector,
      controlMode: initialState.controlMode, ice: this.icePowertrain ? {
        currentFuelL: initialState.currentFuelL, engineRPM: initialState.engineRPM,
        engineRunning: initialState.engineRunning, clutchEngagement: initialState.clutchEngagement,
      } : undefined });
    this.synchronizePowertrainMass();
    if (this.config.driveModes !== undefined) this.setDriveMode('NORMAL');
    this.x = this.finiteOr(initialState.x, 0);
    this.z = this.finiteOr(initialState.z, 0);
    this.yaw = wrapAngle(this.finiteOr(initialState.yaw, 0));
    this.speed = clamp(
      this.finiteOr(initialState.speed, 0),
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );
    this.acceleration = 0;
    this.yawRate = 0;
    this.bodySlipAngle = 0;
    this.lateralVelocity = 0;
    this.contactSlipRecovery = false;
    this.contactSlipHoldTime = 0;
    this.lateralAcceleration = 0;
    this.rearLateralGripFactor = 1;
    this.suspension.reset();
    this.wheelRotation.reset(this.speed);
    this.differential.distributeTorque(0);
    this.rearDifferential?.distributeTorque(0);
    this.awd?.reset();
    this.driverAssists.esc.reset();
    this.initializeWheelStates();
    this.driverAssists.reset(this.powertrain.vehicleOperational);
    this.brakes.reset();
    this.parkingBrake?.reset(this.powertrain.vehicleOperational, this.transmission.getSnapshot().selectedMode === 'P');
    this.autoHold?.reset();
    this.differential.reset(); this.rearDifferential?.reset();
    this.steering.reset();
    this.controlMode = this.powertrain.setControlMode(initialState.controlMode ?? 'normal');
    this.forces = { ...ZERO_FORCES };
    this.previousShiftUp = false;
    this.previousShiftDown = false;
    this.shiftRejected = false;
    this.shiftRejectionReason = null;
    this.shiftEventSequence = 0;
    this.recoveredThisUpdate = false;
    this.storeLastValidState();
    this.updateUpshiftRecommendation();
    return this.getSnapshot();
  }

  public setPose(x: number, z: number, yaw: number, speed = this.speed): void {
    if (![x, z, yaw, speed].every(Number.isFinite)) return;
    this.x = x;
    this.z = z;
    this.yaw = wrapAngle(yaw);
    this.speed = clamp(
      speed,
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );
    this.wheelRotation.reset(this.speed);
    this.differential.distributeTorque(0);
    this.rearDifferential?.distributeTorque(0);
    this.awd?.reset();
    this.driverAssists.esc.reset();
    this.initializeWheelStates();
    this.storeLastValidState();
  }

  /**
   * Import a collision correction without retaining the pre-impact slip state.
   * CollisionSystem owns contact detection and response; this method only keeps
   * the drivetrain's local velocity and body/velocity heading consistent.
   */
  public applyContactCorrection(correction: VehicleContactCorrection): VehicleSnapshotFor<TPowertrain> {
    if (![correction.x, correction.z, correction.velocityX, correction.velocityZ]
      .every(Number.isFinite)) return this.getSnapshot();
    this.x = correction.x;
    this.z = correction.z;
    const sin = Math.sin(this.yaw);
    const cos = Math.cos(this.yaw);
    this.speed = clamp(
      -sin * correction.velocityX - cos * correction.velocityZ,
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );
    const lateral = cos * correction.velocityX - sin * correction.velocityZ;
    // At rest, retain a modest tangent drift rather than dividing by near-zero
    // forward speed. The normal driving solver damps it out progressively.
    this.lateralVelocity = lateral;
    this.bodySlipAngle = Math.abs(this.speed) > 0.05
      ? Math.atan(lateral / this.speed) : 0;
    this.contactSlipRecovery = Math.abs(lateral) > 0.025;
    // Repeated wall contacts refresh this short hold. A normal tyre-slip clamp
    // or its normal recovery must not turn an already corrected wall-tangent
    // velocity into inward motion again on the next 120 Hz step.
    this.contactSlipHoldTime = this.contactSlipRecovery ? 0.12 : 0;
    this.yawRate = clamp(
      this.finiteOr(correction.yawRate, 0),
      -this.config.steering.maximumYawRate,
      this.config.steering.maximumYawRate,
    );
    this.acceleration = 0;
    this.lateralAcceleration = -this.speed * this.yawRate;
    // An impact is an explicit velocity constraint. Remove stored wheel spin
    // energy with it so tyres cannot immediately shove the car into the wall.
    this.constrainWheelRotation(this.speed);
    this.storeLastValidState();
    return this.getSnapshot();
  }

  /**
   * Attempts to crank the engine. Starting in gear is permitted only when the
   * physical clutch is already sufficiently open, so callers can give useful
   * feedback without knowing any drivetrain internals.
   */
  public requestEngineStart(): boolean {
    if (!this.powertrain.requestStart()) return false;
    this.storeLastValidState();
    return true;
  }

  /**
   * Switches ignition off immediately. This is deliberately permitted while
   * moving or in gear; the drivetrain continues to coast/back-drive through
   * the normal clutch model and no pose or velocity state is rewritten.
   */
  public requestEngineStop(): boolean {
    if (!this.powertrain.requestStop()) return false;
    this.updateUpshiftRecommendation();
    this.storeLastValidState();
    return true;
  }

  /** One edge-triggered cockpit command can safely operate both directions. */
  public requestEngineToggle(): EngineToggleResult {
    // Legacy ICE toggle restarts a stall, but still stops a fuel-starved coasting engine.
    const ice = this.icePowertrain;
    const running = ice ? ice.engine.isRunning || ice.engine.isStarting : this.powertrain.vehicleOperational;
    if (running) {
      this.requestEngineStop();
      return 'stopped';
    }
    return this.requestEngineStart() ? 'started' : 'start-rejected';
  }

  /**
   * Request a gear under the active control mode. Normal mode sequences the
   * automatic clutch; Manual mode swaps immediately only when actually open.
   */
  public requestGear(
    requestedGear: Gear,
    mode: VehicleControlMode = this.controlMode,
  ): boolean {
    const rejection = this.powertrain.requestGear(requestedGear, mode, this.speed);
    if (rejection) return this.rejectShift(rejection);
    this.acceptShift(); return true;
  }

  /** PRND uses the safety gate only; it never advances time or reads a device. */
  public requestDriveSelector(selector: DriveSelector, brake = this.brakes.brakeInput): boolean {
    return this.transmission.requestSelector(selector, this.speed, this.lateralVelocity, this.safeUnitInput(brake));
  }

  /** Apply calibration in place: existing subsystems retain their config references. */
  private setDriveMode(mode: import('../config').VehicleDriveMode): void {
    const calibration = this.config.driveModes?.[mode];
    if (!this.capabilities.driveModes || calibration === undefined) return;
    this.driveMode = mode;
    this.driveModeThrottleExponent = calibration.throttleExponent;
    this.powertrain.applyDriveMode?.(calibration);
    this.config.steering.steeringResponse = calibration.steeringResponse;
    this.config.steering.steeringDamping = calibration.steeringDamping;
    if (this.config.awd !== undefined) this.config.awd.accelerationRearTorqueSplit = calibration.accelerationRearTorqueSplit;
  }

  public cycleDriveMode(): void {
    if (this.config.driveModes === undefined) return;
    this.setDriveMode(this.driveMode === 'ECO' ? 'NORMAL' : this.driveMode === 'NORMAL' ? 'SPORT' : 'ECO');
  }

  /** Variable-frame entry point with bounded internal substeps. */
  public update(
    deltaTime: number,
    input: VehicleInputState,
    environment: VehicleEnvironment = {},
  ): VehicleSnapshotFor<TPowertrain> {
    this.recoveredThisUpdate = false;
    this.validateOrRecover();
    this.updateControlMode(input.controlMode);
    if (input.cycleDriveMode) this.cycleDriveMode();
    this.processShiftCommands(input);

    if (!Number.isFinite(deltaTime) || deltaTime <= 0) return this.getSnapshot();
    const maxFrameTime = Math.max(1e-4, this.config.safety.maxFrameTime);
    const maxSubstep = Math.max(1e-4, this.config.safety.maxSubstep);
    const frameTime = Math.min(deltaTime, maxFrameTime);
    const stepCount = Math.max(1, Math.ceil(frameTime / maxSubstep));
    const dt = frameTime / stepCount;

    for (let step = 0; step < stepCount; step += 1) {
      this.integrateStep(dt, input, environment);
    }
    return this.getSnapshot();
  }

  /** Single integration step for tests or an upper-layer fixed-step driver. */
  public stepFixed(
    dt: number,
    input: VehicleInputState,
    environment: VehicleEnvironment = {},
  ): VehicleSnapshotFor<TPowertrain> {
    this.recoveredThisUpdate = false;
    this.validateOrRecover();
    this.updateControlMode(input.controlMode);
    if (input.cycleDriveMode) this.cycleDriveMode();
    this.processShiftCommands(input);
    if (Number.isFinite(dt) && dt > 0) {
      const maxFrameTime = Math.max(1e-4, this.config.safety.maxFrameTime);
      this.integrateStep(Math.min(dt, maxFrameTime), input, environment);
    }
    return this.getSnapshot();
  }

  public getSnapshot(): VehicleSnapshotFor<TPowertrain> {
    this.synchronizeWheelPositions();
    const powertrain = this.powertrain.getSnapshot();
    const transmission = powertrain.transmission;
    return {
      ...powertrain.ice, powertrain,
      vehicleOperational: powertrain.vehicleOperational, driveAvailable: powertrain.driveAvailable,
      baseVehicleMass: this.config.mass,
      effectiveVehicleMass: this.effectiveVehicleMass,
      x: this.x,
      z: this.z,
      yaw: this.yaw,
      speed: this.speed,
      speedKmh: Math.abs(this.speed) * 3.6,
      driveMode: this.driveMode,
      acceleration: this.acceleration,
      yawRate: this.yawRate,
      bodySlipAngle: this.bodySlipAngle,
      lateralVelocity: this.lateralVelocity,
      lateralAcceleration: this.lateralAcceleration,
      rearLateralGripFactor: this.rearLateralGripFactor,
      gear: this.powertrain.gear,
      throttle: this.powertrain.throttle,
      brake: this.brakes.brakeInput,
      handbrake: this.brakes.handbrakeInput,
      steer: this.steering.steeringInput,
      controlMode: this.controlMode,
      shiftRejected: this.shiftRejected,
      shiftRejectionReason: this.shiftRejectionReason,
      shiftEventSequence: this.shiftEventSequence,
      steeringAngle: this.steering.steeringAngle,
      leftRoadWheelAngle: this.steering.leftRoadWheelAngle,
      rightRoadWheelAngle: this.steering.rightRoadWheelAngle,
      steeringWheelAngle: this.steering.steeringWheelAngle,
      forces: { ...this.forces },
      wheels: Object.fromEntries(WHEEL_IDS.map((id) => [id, {
        ...this.wheels[id], worldPosition: { ...this.wheels[id].worldPosition },
        groundNormal: { ...this.wheels[id].groundNormal },
      }])) as Record<WheelId, WheelPhysicsState>,
      chassis: this.suspension.getSnapshot().chassis,
      transmission,
      differential: this.getDifferentialSnapshot(),
      rearDifferential: this.rearDifferential?.getSnapshot(),
      awd: this.awd?.getSnapshot(),
      driverAssists: this.driverAssists.getSnapshot(),
      parkingBrake: this.parkingBrake?.getSnapshot() ?? {
        state: this.brakes.handbrakeInput > .05 ? 'ENGAGED' : 'RELEASED',
        engaged: this.brakes.handbrakeInput > .05, applying: false,
        fraction: this.brakes.handbrakeInput, emergencyBraking: false },
      autoHold: this.autoHold?.getSnapshot() ?? { state: 'OFF', enabled: false, holding: false, releasing: false, pressure: 0 },
      electronicDifferentialActive: this.driverAssists.electronicDifferentialActive,
      recoveredFromInvalidState: this.recoveredThisUpdate,
    } as VehicleSnapshotFor<TPowertrain>;
  }

  private integrateStep(
    dt: number,
    input: VehicleInputState,
    environment: VehicleEnvironment,
  ): void {
    const throttleCommand = Math.pow(this.safeUnitInput(input.throttle), this.driveModeThrottleExponent);
    const brakeCommand = this.safeUnitInput(input.brake);
    const handbrakeCommand = this.safeUnitInput(input.handbrake);
    const steerCommand = clamp(this.finiteOr(input.steering, 0), -1, 1);

    this.awd?.update(dt, throttleCommand, this.wheels, this.powertrain.driveAvailable && this.powertrain.driving);
    this.driverAssists.updateTraction(dt, this.wheels, throttleCommand, this.powertrain.vehicleOperational,
      this.powertrain.driving, this.powertrain.driveAvailable);
    const context = this.powertrainContext;
    context.dt = dt; context.throttle = throttleCommand; context.brake = brakeCommand;
    context.vehicleSpeed = this.speed; context.vehicleLateralSpeed = this.lateralVelocity;
    context.drivenWheelAngularVelocity = this.getDrivenWheelAngularVelocity();
    context.torqueLimitFactor = this.driverAssists.engineTorqueFactor;
    context.clutchPedal = this.safeUnitInput(input.clutchPedal);
    context.selectorRequest = input.driveSelector; context.driveMode = this.driveMode;
    this.powertrain.prepare(context);
    this.brakes.update(dt, brakeCommand, this.capabilities.mechanicalHandbrake && !this.parkingBrake ? handbrakeCommand : 0);
    const mode = this.transmission.getSnapshot().selectedMode;
    const driving = mode === 'D' || mode === 'R';
    this.parkingBrake?.update(dt, handbrakeCommand, Math.hypot(this.speed, this.lateralVelocity),
      this.powertrain.vehicleOperational, mode === 'P', driving, throttleCommand, brakeCommand, this.powertrain.driveAvailable);
    this.autoHold?.update(dt, this.powertrain.vehicleOperational, driving,
      Math.hypot(this.speed, this.lateralVelocity), brakeCommand, throttleCommand,
      this.powertrain.driveAvailable, this.parkingBrake?.state === 'ENGAGED',
      this.parkingBrake !== undefined && ((!this.powertrain.vehicleOperational && this.parkingBrake.config.autoApplyOnIgnitionOff) ||
        (mode === 'P' && this.parkingBrake.config.autoApplyInPark)));
    this.brakes.setHoldingRequests(this.autoHold?.pressure ?? 0, this.parkingBrake?.emergencyDemand ?? 0,
      this.parkingBrake?.config, this.parkingBrake?.fraction ?? 0);
    this.brakes.setTractionRequests(this.driverAssists.differentialBrakeTorques);
    const frontSurfaceGrip = environment.wheelContacts === undefined ?
      Math.max(0, this.finiteOr(environment.surfaceLateralGripMultiplier,
        this.finiteOr(environment.surfaceGripMultiplier, 1))) :
      (environment.wheelContacts.frontLeft.lateralGrip + environment.wheelContacts.frontRight.lateralGrip) * 0.5;
    this.steering.update(dt, steerCommand, this.speed, frontSurfaceGrip);
    const transmissionOutput = this.powertrain.update(context);
    const clutchTorque = transmissionOutput.inputLoadTorque;
    this.synchronizePowertrainMass();

    const dragForce =
      -0.5 *
      this.config.aero.airDensity *
      this.config.aero.dragCoefficient *
      this.config.aero.frontalArea *
      this.speed *
      Math.abs(this.speed);
    const grade = this.getContactGrade(environment);
    const gradeForce = -this.effectiveVehicleMass * this.config.gravity * Math.sin(grade);
    const externalForce = this.finiteOr(environment.externalLongitudinalForce, 0);
    const tyreForces = this.calculateTyreContactForces(
      dt,
      environment,
      grade,
      transmissionOutput.drivenWheelTorque,
      dragForce + gradeForce + externalForce,
    );
    const {
      wheelForce,
      rollingForce,
      rollingMagnitude,
      serviceBrakeForce,
      handbrakeForce,
    } = tyreForces;
    const forceWithoutBrakes =
      wheelForce + dragForce + rollingForce + gradeForce + externalForce;
    const brakeForce = serviceBrakeForce + handbrakeForce;
    const netForce = forceWithoutBrakes + brakeForce;

    this.acceleration = netForce / Math.max(1, this.effectiveVehicleMass) -
      this.lateralVelocity * this.yawRate;
    const previousSpeed = this.speed;
    let nextSpeed = previousSpeed + this.acceleration * dt;

    // Passive resistance and either brake must not numerically push through zero.
    const crossedZero =
      (previousSpeed > 0 && nextSpeed < 0) || (previousSpeed < 0 && nextSpeed > 0);
    const propulsionWouldReverse = Math.abs(wheelForce + gradeForce + externalForce) <
      Math.abs(dragForce + rollingForce + brakeForce);
    if (crossedZero && propulsionWouldReverse) nextSpeed = 0;
    if (Math.abs(nextSpeed) < 0.002 && Math.abs(netForce) < rollingMagnitude + 1) nextSpeed = 0;
    // Only remove numerical residue at rest; normal braking is tyre slip/force.
    if (this.brakes.brakeInput > 0.1 && Math.abs(nextSpeed) < 0.003 &&
      Math.abs(netForce) < this.effectiveVehicleMass * 0.1) nextSpeed = 0;
    if (tyreForces.staticSupported) nextSpeed = 0;
    this.speed = clamp(
      nextSpeed,
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );

    if (transmissionOutput.parkingLocked) {
      // A near-rest parking pawl is a velocity constraint, not an enormous
      // artificial braking force. It also holds gravity on a slope.
      this.speed = 0; this.acceleration = 0; this.lateralVelocity = 0; this.yawRate = 0;
      this.bodySlipAngle = 0; this.contactSlipRecovery = false; this.contactSlipHoldTime = 0;
      this.constrainWheelRotation(0);
    }
    if (tyreForces.staticSupported) {
      this.lateralVelocity = 0; this.yawRate = 0; this.bodySlipAngle = 0;
      this.contactSlipRecovery = false; this.contactSlipHoldTime = 0;
    }

    const averageSpeed = transmissionOutput.parkingLocked ? 0 : (previousSpeed + this.speed) * 0.5;
    if (!transmissionOutput.parkingLocked && !tyreForces.staticSupported) this.integrateLateralDynamics(dt, averageSpeed, tyreForces);
    else this.lateralAcceleration = 0;

    const engineBrakingForce =
      Math.abs(this.speed) > 0.05 && tyreForces.powertrainForce * this.speed < 0 && throttleCommand < 0.05
        ? tyreForces.powertrainForce
        : 0;
    this.forces = {
      wheelForce,
      brakeForce,
      serviceBrakeForce,
      handbrakeForce,
      aerodynamicDragForce: dragForce,
      rollingResistanceForce: rollingForce,
      gradeForce,
      externalForce,
      netForce,
      engineBrakingForce,
      clutchTorque,
      clutchSlipAngularVelocity: transmissionOutput.couplingSlipAngularVelocity,
    };

    this.applyWorldBounds(environment.bounds);
    this.validateOrRecover();
    this.updateUpshiftRecommendation();
  }

  /** Sum four independently limited contact forces and moments in body coordinates. */
  private integrateLateralDynamics(
    dt: number,
    averageSpeed: number,
    contacts: TyreContactForces,
  ): void {
    const absoluteSpeed = Math.abs(averageSpeed);
    const collisionHold = this.contactSlipRecovery && this.contactSlipHoldTime > 0;
    if (collisionHold) {
      this.contactSlipHoldTime = Math.max(0, this.contactSlipHoldTime - dt);
    } else {
      // A small, dissipative contact relaxation damps sustained saturated
      // slides. It never adds yaw or changes the requested steering angle.
      // Grip loss weakens this damping naturally; restored rear grip lets a
      // released parking-brake slide settle instead of continuing to spin.
      const yawDamping = this.config.tires.lateralSlipRecoveryRate * 0.18 *
        Math.min(1, absoluteSpeed / 3) * this.rearLateralGripFactor;
      const yawAcceleration = contacts.yawMoment / Math.max(1, this.config.yawInertia) *
        Math.max(0.05, this.config.steering.yawResponseScale) - this.yawRate * yawDamping;
      this.yawRate += clamp(yawAcceleration, -5, 5) * dt;
      const maximumYawRate = Math.max(0.1, this.config.steering.maximumYawRate);
      this.yawRate = clamp(this.yawRate, -maximumYawRate, maximumYawRate);
      const lateralAcceleration = contacts.lateralForce / Math.max(1, this.effectiveVehicleMass) + averageSpeed * this.yawRate;
      this.lateralVelocity += lateralAcceleration * dt;
      if (absoluteSpeed < 0.4) {
        const restBlend = clamp01(1 - absoluteSpeed / 0.4);
        this.yawRate *= Math.exp(-12 * restBlend * dt);
        this.lateralVelocity *= Math.exp(-12 * restBlend * dt);
      }
      const slipLimit = Math.max(0.05, this.config.tires.maximumBodySlipAngle) * (averageSpeed < 0 ? 0.55 : 1);
      const velocityLimit = Math.max(0.05, absoluteSpeed) * Math.tan(slipLimit);
      if (!this.contactSlipRecovery) this.lateralVelocity = clamp(this.lateralVelocity, -velocityLimit, velocityLimit);
      if (this.contactSlipRecovery && Math.abs(this.lateralVelocity) < 0.025) this.contactSlipRecovery = false;
    }
    this.bodySlipAngle = absoluteSpeed > 0.05 ? Math.atan(this.lateralVelocity / averageSpeed) : 0;
    const middleYaw = this.yaw + this.yawRate * dt * 0.5;
    this.x += (-Math.sin(middleYaw) * averageSpeed +
      Math.cos(middleYaw) * this.lateralVelocity) * dt;
    this.z += (-Math.cos(middleYaw) * averageSpeed -
      Math.sin(middleYaw) * this.lateralVelocity) * dt;
    this.yaw = wrapAngle(this.yaw + this.yawRate * dt);
    this.lateralAcceleration = contacts.lateralForce / Math.max(1, this.effectiveVehicleMass);
  }

  /** Refresh contact metadata after the scene adapter's final pose/collision query. */
  public syncWheelContacts(contacts: WheelContactSet): void {
    this.suspension.synchronizeGroundGeometry(contacts);
    for (const id of WHEEL_IDS) {
      this.wheels[id] = {
        ...this.wheels[id],
        worldPosition: { x: contacts[id].x, y: contacts[id].height + this.config.wheelRadius, z: contacts[id].z },
        surfaceType: contacts[id].surfaceType,
        groundNormal: { ...contacts[id].normal },
      };
    }
  }

  private synchronizeWheelPositions(): void {
    for (const id of WHEEL_IDS) {
      const local = wheelLocalPosition(this.config, id);
      this.wheels[id] = {
        ...this.wheels[id],
        worldPosition: {
          x: this.x + local.x * Math.cos(this.yaw) + local.z * Math.sin(this.yaw),
          y: this.wheels[id].worldPosition.y,
          z: this.z - local.x * Math.sin(this.yaw) + local.z * Math.cos(this.yaw),
        },
      };
    }
  }

  /** Contact normals provide longitudinal slope, including heading across a ramp. */
  private getContactGrade(environment: VehicleEnvironment): number {
    const contacts = environment.wheelContacts;
    const normals = contacts === undefined
      ? (environment.groundNormal === undefined ? [] : [environment.groundNormal])
      : [contacts.frontLeft.normal, contacts.frontRight.normal,
        contacts.rearLeft.normal, contacts.rearRight.normal];
    if (normals.length === 0) return clamp(
      this.finiteOr(environment.gradeRadians, 0), -Math.PI * 0.45, Math.PI * 0.45,
    );
    let x = 0;
    let y = 0;
    let z = 0;
    for (const normal of normals) {
      x += this.finiteOr(normal.x, 0);
      y += Math.max(0, this.finiteOr(normal.y, 1));
      z += this.finiteOr(normal.z, 0);
    }
    // dy/ds = -(normal dot forward) / normal.y, forward=(-sin yaw,-cos yaw).
    return clamp(Math.atan2(x * Math.sin(this.yaw) + z * Math.cos(this.yaw),
      Math.max(1e-4, y)), -Math.PI * 0.45, Math.PI * 0.45);
  }

  /**
   * Static axle load is divided across four contacts. Each tyre gets its own
   * drive, brake and resistance budget, so straddling a boundary changes only
   * the contacting side instead of switching the entire car's material.
   */
  private calculateTyreContactForces(
    dt: number,
    environment: VehicleEnvironment,
    grade: number,
    requestedDriveTorque: number,
    otherLongitudinalForce: number,
  ): TyreContactForces {
    const suspension = this.suspension.update(dt, {
      contacts: environment.wheelContacts,
      normal: environment.groundNormal ?? { x: 0, y: Math.cos(grade), z: Math.sin(grade) },
      // Coordinate-speed derivative also contains -v_lateral*yawRate; load
      // transfer must use the actual body-forward force acceleration instead.
      longitudinalAcceleration: this.forces.netForce / Math.max(1, this.effectiveVehicleMass),
      lateralAcceleration: this.lateralAcceleration,
    });
    const frontWeight = clamp(this.config.frontWeightBias, 0.05, 0.95);
    const shares: FourWheelValues = [frontWeight * 0.5, frontWeight * 0.5,
      (1 - frontWeight) * 0.5, (1 - frontWeight) * 0.5];
    const localX: FourWheelValues = [-this.config.frontTrackWidth * 0.5,
      this.config.frontTrackWidth * 0.5, -this.config.rearTrackWidth * 0.5,
      this.config.rearTrackWidth * 0.5];
    const wheelContacts = environment.wheelContacts;
    const contacts = wheelContacts === undefined ? undefined : [
      wheelContacts.frontLeft, wheelContacts.frontRight,
      wheelContacts.rearLeft, wheelContacts.rearRight,
    ];
    const sharedGrip = Math.max(0, this.finiteOr(environment.surfaceGripMultiplier, 1));
    const legacyLongitudinal = sharedGrip * Math.max(0,
      this.finiteOr(environment.surfaceLongitudinalGripMultiplier, 1));
    const legacyLateral = sharedGrip * Math.max(0,
      this.finiteOr(environment.surfaceLateralGripMultiplier, 1));
    const legacyRolling = Math.max(0,
      this.finiteOr(environment.rollingResistanceMultiplier, 1));
    const gripLong = shares.map((_, i) => Math.max(0,
      this.finiteOr(contacts?.[i]?.longitudinalGrip, legacyLongitudinal))) as FourWheelValues;
    const gripLat = shares.map((_, i) => Math.max(0,
      this.finiteOr(contacts?.[i]?.lateralGrip, legacyLateral))) as FourWheelValues;
    const rolling = shares.map((_, i) => Math.max(0,
      this.finiteOr(contacts?.[i]?.rollingResistance, legacyRolling))) as FourWheelValues;
    const loads = WHEEL_IDS.map((id) => suspension.wheels[id].normalLoad) as FourWheelValues;
    const limits = loads.map((load, i) => this.config.tires.longitudinalGrip * load *
      this.wheelRotation.gripModel.loadFactor(load, suspension.wheels[WHEEL_IDS[i]!].staticLoad) * gripLong[i]!) as FourWheelValues;
    for (let i = 0; i < 4; i++) this.escLateralLimits[i] = this.config.tires.lateralGrip * loads[i]! *
      this.wheelRotation.gripModel.loadFactor(loads[i]!, suspension.wheels[WHEEL_IDS[i]!].staticLoad) * gripLat[i]!;
    this.driverAssists.updateStability(dt, this.speed, this.steering.steeringAngle,
      this.yawRate, this.lateralVelocity, this.wheels, limits, this.escLateralLimits);
    this.brakes.setDriverAidState(this.driverAssists.frontBrakeBias, this.driverAssists.pressures, this.driverAssists.esc.brakeTorques);
    this.brakes.prepareRequests();
    this.driverAssists.updateBrakes(dt, this.speed, this.brakes.brakeInput, this.wheels, limits, this.brakes.coordinator);
    this.brakes.setDriverAidState(this.driverAssists.frontBrakeBias, this.driverAssists.pressures, this.driverAssists.esc.brakeTorques);
    // Transmission owns final drive/efficiency; AWD owns axle shares and each
    // configured carrier owns left/right torque distribution.
    this.differential.distributeTorque(requestedDriveTorque * (this.awd ? 1 - this.awd.rearTorqueSplit : 1), dt);
    this.rearDifferential?.distributeTorque(requestedDriveTorque * (this.awd?.rearTorqueSplit ?? 0), dt);
    const requestedDrive: FourWheelValues = this.rearDifferential
      ? [this.differential.leftTorque, this.differential.rightTorque, this.rearDifferential.leftTorque, this.rearDifferential.rightTorque]
      : this.differential.axle === 'front'
      ? [this.differential.leftTorque, this.differential.rightTorque, 0, 0]
      : [0, 0, this.differential.leftTorque, this.differential.rightTorque];
    const rollingMagnitudes = loads.map((load, i) =>
      this.config.tires.rollingResistance * load * rolling[i]!) as FourWheelValues;
    const rollingForces = rollingMagnitudes.map((magnitude, i) =>
      -magnitude * Math.tanh((this.speed + this.yawRate * localX[i]!) / 0.2)) as FourWheelValues;
    const sum = (values: number[]): number => values.reduce((total, value) => total + value, 0);
    const usage: FourWheelValues = [0, 0, 0, 0];
    const lateral: FourWheelValues = [0, 0, 0, 0];
    const lateralLimits: FourWheelValues = [0, 0, 0, 0];
    const angles: FourWheelValues = [this.steering.leftRoadWheelAngle, this.steering.rightRoadWheelAngle, 0, 0];
    const brakeTorques = WHEEL_IDS.map(id => this.brakes.getWheelTorques(id));
    // A stopped tyre supports static shear on a hill even with zero slip.
    // Solve that dry-contact constraint only near rest and only within actual
    // brake torque AND tyre grip. Moving/locked-wheel braking keeps real slip.
    let staticForces: FourWheelValues | undefined;
    if (Math.hypot(this.speed, this.lateralVelocity) < 0.08 && Math.abs(this.yawRate) < 0.03 &&
      brakeTorques.some(b => b.appliedBrakeTorque + b.appliedHandbrakeTorque > 1) &&
      WHEEL_IDS.every(id => Math.abs(this.wheelRotation.getAngularVelocity(id) * this.config.wheelRadius) < 0.12)) {
      const minimum: FourWheelValues = [0, 0, 0, 0];
      const maximum: FourWheelValues = [0, 0, 0, 0];
      for (const i of [0, 1, 2, 3] as const) {
        const brake = brakeTorques[i]!;
        const capacity = brake.appliedBrakeTorque + brake.appliedHandbrakeTorque;
        const inertiaTorque = this.config.tires.wheelInertia *
          this.wheelRotation.getAngularVelocity(WHEEL_IDS[i]) / Math.max(1e-4, dt);
        const cosine = Math.cos(angles[i]);
        minimum[i] = Math.max(-limits[i], (requestedDrive[i] + inertiaTorque - capacity) /
          this.config.wheelRadius) * cosine;
        maximum[i] = Math.min(limits[i], (requestedDrive[i] + inertiaTorque + capacity) /
          this.config.wheelRadius) * cosine;
      }
      const required = -otherLongitudinalForce - sum(rollingForces.map((f, i) => f * Math.cos(angles[i]!))) -
        this.effectiveVehicleMass * this.speed / Math.max(1e-4, dt);
      const lower = sum(minimum); const upper = sum(maximum);
      if (minimum.every((v, i) => v <= maximum[i]!) && required >= lower && required <= upper) {
        const blend = upper - lower > 1e-6 ? (required - lower) / (upper - lower) : 0;
        staticForces = minimum.map((v, i) => (v + (maximum[i]! - v) * blend) /
          Math.cos(angles[i]!)) as FourWheelValues;
      }
    }
    const driveBody: FourWheelValues = [0, 0, 0, 0];
    const inertiaBody: FourWheelValues = [0, 0, 0, 0];
    const serviceBody: FourWheelValues = [0, 0, 0, 0];
    const handbrakeBody: FourWheelValues = [0, 0, 0, 0];
    const rollingBody: FourWheelValues = [0, 0, 0, 0];
    const lateralScrub: FourWheelValues = [0, 0, 0, 0];
    const rearAvailability: number[] = [];
    let asymmetricLongitudinalMoment = 0;
    let totalYawMoment = 0;
    const distanceToFront = clamp(this.config.wheelBase * (1 - frontWeight) -
      this.config.centerOfMassLongitudinalOffset, this.config.wheelBase * 0.1, this.config.wheelBase * 0.9);
    const distanceToRear = this.config.wheelBase - distanceToFront;
    const longitudinalPositions: FourWheelValues = [distanceToFront, distanceToFront, -distanceToRear, -distanceToRear];
    let staticSupported = staticForces !== undefined;
    for (const i of [0, 1, 2, 3] as const) {
      const id = WHEEL_IDS[i];
      const cosine = Math.cos(angles[i]);
      const sine = Math.sin(angles[i]);
      const wheelForwardVelocity = this.speed + this.yawRate * localX[i];
      const wheelLateralVelocity = this.lateralVelocity - this.yawRate * longitudinalPositions[i];
      const brake = brakeTorques[i]!;
      const handbrakeUsage = limits[i] > 1 ? clamp01(brake.appliedHandbrakeTorque / this.config.wheelRadius / limits[i]) : 0;
      const lockedRearAvailability = 1 - (1 - clamp01(this.config.tires.handbrakeRearGripFactor)) *
        handbrakeUsage * handbrakeUsage * (3 - 2 * handbrakeUsage);
      if (i >= 2) rearAvailability.push(lockedRearAvailability);
      const staticLoad = suspension.wheels[id].staticLoad;
      const loadStiffness = Math.max(0.1, loads[i] / Math.max(1, staticLoad));
      const corneringStiffness = (i < 2 ? this.config.tires.corneringStiffnessFront : this.config.tires.corneringStiffnessRear) * 0.5 * loadStiffness;
      const rotation = this.wheelRotation.updateWheel(id, dt, {
        longitudinalSpeed: wheelForwardVelocity * cosine + wheelLateralVelocity * sine,
        lateralSpeed: wheelLateralVelocity * cosine - wheelForwardVelocity * sine,
        driveTorque: requestedDrive[i], brakeTorque: brake.appliedBrakeTorque,
        handbrakeTorque: brake.appliedHandbrakeTorque, normalLoad: loads[i],
        surfaceLongitudinalGrip: gripLong[i],
        staticNormalLoad: staticLoad, surfaceLateralGrip: gripLat[i],
        corneringStiffness, lateralGripAvailability: lockedRearAvailability,
        staticLongitudinalForce: staticForces?.[i],
      });
      staticSupported = staticSupported && rotation.staticContact;
      const tyreForce = rotation.longitudinalForce;
      usage[i] = rotation.longitudinalUsage;
      lateralLimits[i] = rotation.lateralForceLimit;
      const slipAngle = rotation.slipAngle;
      const tyreLateral = rotation.lateralForce;
      // Torque-derived diagnostics close exactly with wheel inertia. Only the
      // actual slip-derived Fx enters the chassis: never sum the demands twice.
      const driveForce = requestedDrive[i] / this.config.wheelRadius;
      const serviceForce = -rotation.brakeReactionTorque / this.config.wheelRadius;
      const handbrakeForce = -rotation.handbrakeReactionTorque / this.config.wheelRadius;
      driveBody[i] = driveForce * cosine;
      inertiaBody[i] = rotation.rotationalInertiaForce * cosine;
      serviceBody[i] = serviceForce * cosine;
      handbrakeBody[i] = handbrakeForce * cosine;
      rollingBody[i] = rollingForces[i] * cosine;
      lateralScrub[i] = -tyreLateral * sine;
      const longitudinal = (tyreForce + rollingForces[i]) * cosine + lateralScrub[i];
      lateral[i] = (tyreForce + rollingForces[i]) * sine + tyreLateral * cosine;
      asymmetricLongitudinalMoment += localX[i] * (tyreForce + rollingForces[i]);
      totalYawMoment += localX[i] * longitudinal - longitudinalPositions[i] * lateral[i];
      const localWheel = wheelLocalPosition(this.config, id);
      const worldX = this.x + localWheel.x * Math.cos(this.yaw) + localWheel.z * Math.sin(this.yaw);
      const worldZ = this.z - localWheel.x * Math.sin(this.yaw) + localWheel.z * Math.cos(this.yaw);
      const spring = suspension.wheels[id];
      this.wheels[id] = {
        id,
        worldPosition: { x: contacts?.[i]?.x ?? worldX, y: (contacts?.[i]?.height ?? 0) + this.config.wheelRadius, z: contacts?.[i]?.z ?? worldZ },
        surfaceType: contacts?.[i]?.surfaceType ?? 'asphalt',
        groundNormal: { ...(contacts?.[i]?.normal ?? environment.groundNormal ?? { x: 0, y: Math.cos(grade), z: Math.sin(grade) }) },
        normalLoad: loads[i], steeringAngle: angles[i],
        driveTorque: requestedDrive[i], driveForce,
        brakeTorque: brake.appliedBrakeTorque, requestedBrakeTorque: brake.requestedBrakeTorque,
        appliedBrakeTorque: brake.appliedBrakeTorque, brakeForce: serviceForce,
        handbrakeTorque: brake.appliedHandbrakeTorque, requestedHandbrakeTorque: brake.requestedHandbrakeTorque,
        appliedHandbrakeTorque: brake.appliedHandbrakeTorque, handbrakeForce,
        rollingResistanceForce: rollingForces[i], longitudinalForce: tyreForce, lateralForce: tyreLateral,
        suspensionCompression: spring.compression, suspensionVelocity: spring.compressionVelocity,
        suspensionRestCompression: spring.restCompression, springForce: spring.springForce, damperForce: spring.damperForce,
        angularVelocity: rotation.angularVelocity, wheelAngularVelocity: rotation.angularVelocity,
        rotationAngle: rotation.rotationAngle, longitudinalSpeed: rotation.longitudinalSpeed,
        lateralSpeed: rotation.lateralSpeed, slipRatio: rotation.slipRatio, slipAngle,
        longitudinalUsage: rotation.longitudinalUsage, lateralUsage: rotation.lateralUsage, gripUsage: rotation.gripUsage,
      };
    }
    this.rearLateralGripFactor = rearAvailability.reduce((total, value) => total + value, 0) * 0.5;
    return {
      staticSupported,
      wheelForce: sum(driveBody) + sum(inertiaBody) + sum(lateralScrub),
      powertrainForce: sum(driveBody),
      serviceBrakeForce: sum(serviceBody),
      handbrakeForce: sum(handbrakeBody),
      rollingForce: sum(rollingBody),
      rollingMagnitude: sum(rollingMagnitudes),
      longitudinalForceLimit: sum(limits),
      frontLateralGrip: (gripLat[0] + gripLat[1]) * 0.5,
      rearLateralGrip: (gripLat[2] + gripLat[3]) * 0.5,
      frontLongitudinalUsage: (usage[0] + usage[1]) * 0.5,
      rearLongitudinalUsage: (usage[2] + usage[3]) * 0.5,
      contactYawAcceleration: clamp(asymmetricLongitudinalMoment / Math.max(1, this.config.yawInertia) *
        clamp01(this.config.tires.contactYawInfluence), -0.65, 0.65),
      lateralForce: sum(lateral),
      yawMoment: totalYawMoment,
      lateralForceLimit: sum(lateralLimits),
    };
  }

  private initializeWheelStates(): void {
    const springs = this.suspension.getSnapshot();
    for (const id of WHEEL_IDS) {
      const local = wheelLocalPosition(this.config, id);
      const spring = springs.wheels[id];
      const rotation = this.wheelRotation.getSnapshot(id);
      this.wheels[id] = {
        id, worldPosition: { x: this.x + local.x * Math.cos(this.yaw) + local.z * Math.sin(this.yaw), y: this.config.wheelRadius,
          z: this.z - local.x * Math.sin(this.yaw) + local.z * Math.cos(this.yaw) },
        surfaceType: 'asphalt', groundNormal: { x: 0, y: 1, z: 0 }, normalLoad: spring.normalLoad,
        steeringAngle: 0, driveTorque: 0, driveForce: 0, brakeTorque: 0, brakeForce: 0,
        requestedBrakeTorque: 0, appliedBrakeTorque: 0,
        handbrakeTorque: 0, handbrakeForce: 0, rollingResistanceForce: 0, longitudinalForce: 0, lateralForce: 0,
        requestedHandbrakeTorque: 0, appliedHandbrakeTorque: 0,
        suspensionCompression: spring.compression, suspensionVelocity: 0, suspensionRestCompression: spring.restCompression,
        springForce: spring.springForce, damperForce: 0,
        angularVelocity: rotation.angularVelocity, wheelAngularVelocity: rotation.angularVelocity,
        rotationAngle: rotation.rotationAngle, longitudinalSpeed: rotation.longitudinalSpeed,
        lateralSpeed: 0, slipRatio: 0, slipAngle: 0,
        longitudinalUsage: 0, lateralUsage: 0, gripUsage: 0,
      };
    }
  }

  /** Only a discontinuous contact/pawl constraint may synchronise wheel spin. */
  private constrainWheelRotation(speed: number): void {
    for (const id of WHEEL_IDS) {
      const local = wheelLocalPosition(this.config, id);
      const angle = this.wheels[id].steeringAngle;
      const forward = speed + this.yawRate * local.x;
      const side = this.lateralVelocity + this.yawRate * local.z;
      const longitudinalSpeed = forward * Math.cos(angle) + side * Math.sin(angle);
      const lateralSpeed = side * Math.cos(angle) - forward * Math.sin(angle);
      this.wheelRotation.constrainAngularVelocity(id, longitudinalSpeed / Math.max(0.01, this.config.wheelRadius),
        longitudinalSpeed, lateralSpeed);
      const rotation = this.wheelRotation.getSnapshot(id);
      this.wheels[id] = { ...this.wheels[id], angularVelocity: rotation.angularVelocity,
        wheelAngularVelocity: rotation.angularVelocity, rotationAngle: rotation.rotationAngle,
        longitudinalSpeed, lateralSpeed, slipRatio: rotation.slipRatio, slipAngle: rotation.slipAngle,
        longitudinalForce: 0, lateralForce: 0, driveForce: 0, brakeForce: 0, handbrakeForce: 0,
        rollingResistanceForce: 0, longitudinalUsage: 0, lateralUsage: 0, gripUsage: 0 };
    }
  }

  private getDrivenWheelAngularVelocity(): number {
    if (this.awd && this.rearDifferential) {
      const front = this.differential.updateSpeeds(this.wheelRotation.getAngularVelocity('frontLeft'),
        this.wheelRotation.getAngularVelocity('frontRight'));
      const rear = this.rearDifferential.updateSpeeds(this.wheelRotation.getAngularVelocity('rearLeft'),
        this.wheelRotation.getAngularVelocity('rearRight'));
      return this.awd.updateSpeeds(front, rear);
    }
    const front = this.differential.axle === 'front';
    return this.differential.updateSpeeds(
      this.wheelRotation.getAngularVelocity(front ? 'frontLeft' : 'rearLeft'),
      this.wheelRotation.getAngularVelocity(front ? 'frontRight' : 'rearRight'));
  }

  private getDifferentialSnapshot(): DifferentialSnapshot {
    this.getDrivenWheelAngularVelocity();
    return this.differential.getSnapshot();
  }

  private updateControlMode(requestedMode: VehicleControlMode): void {
    this.controlMode = this.powertrain.setControlMode(requestedMode);
  }

  private processShiftCommands(input: VehicleInputState): void {
    const shiftUp = input.shiftUp === true;
    const shiftDown = input.shiftDown === true;
    if (this.transmission.type !== 'MANUAL') {
      // Near-rest brake gating separates PRND requests from optional D ratio requests.
      // Stop at the ends: D must never wrap straight into P. Explicit selector
      // requests take priority and use the existing prepare/safety path.
      const direction = shiftUp && !this.previousShiftUp && !shiftDown ? 1
        : shiftDown && !this.previousShiftDown && !shiftUp ? -1 : 0;
      if (input.returnToAuto === true) this.transmission.returnToAuto?.();
      if (input.driveSelector === undefined && direction !== 0) {
        const current = this.transmission.getSnapshot().selectedMode ?? 'P';
        const selectorAllowed = Math.hypot(this.speed, this.lateralVelocity) < 2 / 3.6 && input.brake >= .1;
        if (selectorAllowed) {
          const selectors: readonly DriveSelector[] = ['P', 'R', 'N', 'D'];
          const next = selectors[selectors.indexOf(current) + direction];
          if (next !== undefined) this.requestDriveSelector(next, input.brake);
        } else if (current === 'D' && this.capabilities.manualSelection && input.returnToAuto !== true) {
          this.transmission.requestManualSelection?.(direction);
        }
      }
    } else if (input.directGear !== undefined) {
      this.requestGear(input.directGear, this.controlMode);
    } else if (shiftUp && !this.previousShiftUp && !shiftDown) {
      const gear = this.powertrain.getShiftGear(1);
      if (gear !== null) this.requestGear(gear, this.controlMode);
    } else if (shiftDown && !this.previousShiftDown && !shiftUp) {
      const gear = this.powertrain.getShiftGear(-1);
      if (gear !== null) this.requestGear(gear, this.controlMode);
    }
    this.previousShiftUp = shiftUp;
    this.previousShiftDown = shiftDown;
  }

  private acceptShift(): void {
    this.shiftRejected = false;
    this.shiftRejectionReason = null;
    this.shiftEventSequence += 1;
  }

  private rejectShift(reason: ShiftRejectionReason): false {
    this.shiftRejected = true;
    this.shiftRejectionReason = reason;
    this.shiftEventSequence += 1;
    return false;
  }

  private applyWorldBounds(bounds: VehicleWorldBounds | undefined): void {
    if (bounds === undefined) return;
    if (![bounds.minX, bounds.maxX, bounds.minZ, bounds.maxZ].every(Number.isFinite)) return;
    if (bounds.minX > bounds.maxX || bounds.minZ > bounds.maxZ) return;
    const boundedX = clamp(this.x, bounds.minX, bounds.maxX);
    const boundedZ = clamp(this.z, bounds.minZ, bounds.maxZ);
    if (boundedX !== this.x || boundedZ !== this.z) {
      this.x = boundedX;
      this.z = boundedZ;
      this.speed = 0;
      this.acceleration = 0;
      this.yawRate = 0;
      this.bodySlipAngle = 0;
      this.lateralVelocity = 0;
      this.lateralAcceleration = 0;
      this.constrainWheelRotation(0);
    }
  }

  private validateOrRecover(): void {
    const values = [
      this.x,
      this.z,
      this.yaw,
      this.speed,
      this.acceleration,
      this.yawRate,
      this.bodySlipAngle,
      this.lateralVelocity,
      this.lateralAcceleration,
      this.rearLateralGripFactor,
      this.torqueSource.shaftAngularVelocity,
      this.powertrain.variableMassKg,
      this.brakes.brakeInput,
      this.brakes.handbrakeInput,
      ...WHEEL_IDS.flatMap(id => [this.wheelRotation.getSnapshot(id).angularVelocity,
        this.wheelRotation.getSnapshot(id).rotationAngle, this.wheels[id].slipRatio]),
    ];
    const positionIsReasonable =
      Math.abs(this.x) <= this.config.safety.maxAbsPosition &&
      Math.abs(this.z) <= this.config.safety.maxAbsPosition;
    if (this.powertrain.numericallyValid && values.every(Number.isFinite) && positionIsReasonable) {
      this.storeLastValidState();
      return;
    }

    this.x = this.lastValidState.x;
    this.z = this.lastValidState.z;
    this.yaw = this.lastValidState.yaw;
    this.speed = this.lastValidState.speed;
    this.acceleration = 0;
    this.yawRate = this.lastValidState.yawRate;
    this.bodySlipAngle = this.lastValidState.bodySlipAngle;
    this.lateralVelocity = this.lastValidState.lateralVelocity;
    this.contactSlipRecovery = this.lastValidState.contactSlipRecovery;
    this.contactSlipHoldTime = this.lastValidState.contactSlipHoldTime;
    this.lateralAcceleration = -this.speed * this.yawRate;
    this.rearLateralGripFactor = 1;
    this.powertrain.reset(this.lastValidState.powertrain, true);
    this.controlMode = this.lastValidState.controlMode;
    this.synchronizePowertrainMass();
    this.brakes.reset();
    this.parkingBrake?.reset(this.powertrain.vehicleOperational, this.transmission.getSnapshot().selectedMode === 'P');
    this.autoHold?.reset();
    this.differential.reset(); this.rearDifferential?.reset();
    this.steering.reset();
    this.suspension.reset();
    this.wheelRotation.reset(this.speed);
    this.differential.distributeTorque(0);
    this.rearDifferential?.distributeTorque(0);
    this.awd?.reset();
    this.driverAssists.esc.reset();
    this.initializeWheelStates();
    this.forces = { ...ZERO_FORCES };
    this.recoveredThisUpdate = true;
  }

  private storeLastValidState(): void {
    const state = this.lastValidState;
    state.x = this.x; state.z = this.z; state.yaw = this.yaw; state.speed = this.speed;
    state.controlMode = this.controlMode; state.bodySlipAngle = this.bodySlipAngle;
    state.lateralVelocity = this.lateralVelocity; state.contactSlipRecovery = this.contactSlipRecovery;
    state.contactSlipHoldTime = this.contactSlipHoldTime; state.yawRate = this.yawRate;
    state.powertrain = this.powertrain.captureState(state.powertrain);
  }

  private safeUnitInput(value: number): number {
    return clamp01(this.finiteOr(value, 0));
  }

  private updateUpshiftRecommendation(): void { this.powertrain.finishStep(this.speed); }

  private finiteOr(value: number | undefined, fallback: number): number {
    return value !== undefined && Number.isFinite(value) ? value : fallback;
  }

}
