import type { VehicleControlMode, VehicleInputState } from '../../input/VehicleInputState';
import {
  createDefaultVehiclePhysicsConfig,
  type Gear,
  type DriveSelector,
  type VehiclePhysicsConfig,
} from '../config';
import {
  AutoClutchController,
  type AutoClutchState,
  type AutoClutchUpdateResult,
} from './AutoClutchController';
import { BrakeSystem } from './BrakeSystem';
import { DriverAssistSystem, type DriverAssistOptions, type DriverAssistSnapshot } from './DriverAssistSystem';
import { Clutch, type ClutchState } from './Clutch';
import { Engine, type RevHangSnapshot } from './Engine';
import { DrivetrainLash, type DrivetrainLashSnapshot } from './DrivetrainLash';
import { Gearbox } from './Gearbox';
import { SteeringSystem } from './SteeringSystem';
import { UpshiftAdvisor } from './UpshiftAdvisor';
import { WHEEL_IDS, type WheelContactSet, type WheelId } from './WheelContact';
import { wheelLocalPosition } from '../VehicleDimensions';
import { SuspensionSystem } from './SuspensionSystem';
import { WheelRotationSystem } from './WheelRotationSystem';
import { OpenDifferential, type OpenDifferentialSnapshot } from './OpenDifferential';
import type { ChassisPhysicsState, WheelPhysicsState, WheelPhysicsStateSet } from './WheelPhysicsState';
import { clamp, clamp01, wrapAngle } from './math';
import { createTransmissionSystem } from '../transmission/createTransmissionSystem';
import type { TransmissionContext, TransmissionSnapshot, TransmissionSystem } from '../transmission/TransmissionSystem';

export interface VehicleWorldBounds {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
}

/** Per-step road information supplied by the world/track system. */
export interface VehicleEnvironment {
  /** Four independently queried tyre contacts; material coefficients are relative to asphalt. */
  wheelContacts?: WheelContactSet;
  /** Upward unit surface normal. Wheel-contact normals take priority when present. */
  groundNormal?: { x: number; y: number; z: number };
  /** Positive means uphill in the vehicle's local forward direction. */
  gradeRadians?: number;
  /** Multiplier for wet, gravel, etc. One is the configured dry-road grip. */
  surfaceGripMultiplier?: number;
  /** Optional axle-independent overrides layered on top of surfaceGripMultiplier. */
  surfaceLongitudinalGripMultiplier?: number;
  surfaceLateralGripMultiplier?: number;
  rollingResistanceMultiplier?: number;
  /** Wind/collisions may inject a signed force without entering the drivetrain. */
  externalLongitudinalForce?: number;
  bounds?: VehicleWorldBounds;
}

/** Pose/velocity returned by the separate, planar static collision resolver. */
export interface VehicleContactCorrection {
  x: number;
  z: number;
  velocityX: number;
  velocityZ: number;
  yawRate?: number;
}

interface TyreContactForces {
  staticSupported: boolean;
  wheelForce: number;
  powertrainForce: number;
  serviceBrakeForce: number;
  handbrakeForce: number;
  rollingForce: number;
  rollingMagnitude: number;
  longitudinalForceLimit: number;
  frontLateralGrip: number;
  rearLateralGrip: number;
  frontLongitudinalUsage: number;
  rearLongitudinalUsage: number;
  contactYawAcceleration: number;
  lateralForce: number;
  yawMoment: number;
  lateralForceLimit: number;
}

type FourWheelValues = [number, number, number, number];

export interface VehicleInitialState {
  x?: number;
  z?: number;
  yaw?: number;
  speed?: number;
  gear?: Gear;
  engineRPM?: number;
  /** Defaults to true; false creates a stopped/stalled engine at zero rpm. */
  engineRunning?: boolean;
  clutchEngagement?: number;
  controlMode?: VehicleControlMode;
  driveSelector?: DriveSelector;
}

export type ShiftRejectionReason =
  | 'clutch-not-disengaged'
  | 'engine-over-speed'
  | 'gear-not-available'
  | 'already-selected'
  | 'shift-in-progress';

/** Result lets the UI distinguish a successful stop from a blocked restart. */
export type EngineToggleResult = 'started' | 'stopped' | 'start-rejected';

export interface VehicleForceSnapshot {
  /** Signed tyre force generated by the powertrain, including back-drive. */
  wheelForce: number;
  /** Combined applied service-brake and handbrake force. */
  brakeForce: number;
  serviceBrakeForce: number;
  handbrakeForce: number;
  aerodynamicDragForce: number;
  rollingResistanceForce: number;
  gradeForce: number;
  externalForce: number;
  netForce: number;
  /** Signed subset of wheelForce that opposes motion with the throttle shut. */
  engineBrakingForce: number;
  /** Torque crossing the clutch; exposed for slip/capacity diagnostics. */
  clutchTorque: number;
  clutchSlipAngularVelocity: number;
}

export interface VehicleSnapshot {
  x: number;
  z: number;
  yaw: number;
  speed: number;
  speedKmh: number;
  acceleration: number;
  yawRate: number;
  /** Velocity direction relative to the body; positive points toward vehicle-right. */
  bodySlipAngle: number;
  /** Signed body-local lateral velocity, in m/s. */
  lateralVelocity: number;
  /** Signed body-local lateral acceleration; positive is vehicle-right. */
  lateralAcceleration: number;
  /** Remaining rear lateral authority after parking-brake lockup. */
  rearLateralGripFactor: number;
  rpm: number;
  /** False after a stall and until a valid start request succeeds. */
  engineRunning: boolean;
  idleRPM: number;
  /** Compatibility alias for the current load-dependent recommendation. */
  shiftWarningRPM: number;
  /** Everyday-driving target; intentionally far below the engine redline. */
  recommendedUpshiftRPM: number;
  upshiftRecommendationAvailable: boolean;
  upshiftRecommended: boolean;
  redlineWarningRPM: number;
  nearRedline: boolean;
  onRevLimiter: boolean;
  redlineRPM: number;
  gear: Gear;
  requestedGear: Gear | null;
  throttle: number;
  brake: number;
  handbrake: number;
  steer: number;
  controlMode: VehicleControlMode;
  /** Pedal down = 1; deliberately distinct from mechanical engagement. */
  clutchPedal: number;
  clutchEngagement: number;
  clutchState: ClutchState;
  autoClutchState: AutoClutchState;
  /** State of the most recent shift event; compare sequence for a new event. */
  shiftRejected: boolean;
  shiftRejectionReason: ShiftRejectionReason | null;
  shiftEventSequence: number;
  steeringAngle: number;
  /** Individual visual/diagnostic road-wheel angles after Ackermann correction. */
  leftRoadWheelAngle: number;
  rightRoadWheelAngle: number;
  steeringWheelAngle: number;
  forces: VehicleForceSnapshot;
  wheels: WheelPhysicsStateSet;
  chassis: ChassisPhysicsState;
  transmission: TransmissionSnapshot;
  drivetrainLash: DrivetrainLashSnapshot;
  revHang: RevHangSnapshot;
  differential: OpenDifferentialSnapshot;
  driverAssists: DriverAssistSnapshot;
  /** True for the update in which corrupt numeric state was restored. */
  recoveredFromInvalidState: boolean;
}

interface ValidCoreState {
  x: number;
  z: number;
  yaw: number;
  speed: number;
  rpm: number;
  engineRunning: boolean;
  gear: Gear;
  clutchEngagement: number;
  controlMode: VehicleControlMode;
  bodySlipAngle: number;
  lateralVelocity: number;
  contactSlipRecovery: boolean;
  contactSlipHoldTime: number;
  yawRate: number;
  driveSelector?: DriveSelector;
}

const ZERO_FORCES: VehicleForceSnapshot = {
  wheelForce: 0,
  brakeForce: 0,
  serviceBrakeForce: 0,
  handbrakeForce: 0,
  aerodynamicDragForce: 0,
  rollingResistanceForce: 0,
  gradeForce: 0,
  externalForce: 0,
  netForce: 0,
  engineBrakingForce: 0,
  clutchTorque: 0,
  clutchSlipAngularVelocity: 0,
};

/**
 * Four independent supported wheel contacts and a planar chassis. This class
 * consumes only the normalized VehicleInputState contract. It has no knowledge
 * of keyboards, gamepads, steering wheels, renderers, or wall-clock time.
 */
export class VehicleDynamics {
  public readonly engine: Engine;
  public readonly clutch: Clutch;
  public readonly autoClutch: AutoClutchController;
  public readonly gearbox: Gearbox;
  public readonly brakes: BrakeSystem;
  public readonly driverAssists: DriverAssistSystem;
  public setDriverAssistOptions(options: DriverAssistOptions): void { this.driverAssists.setOptions(options); }
  public readonly steering: SteeringSystem;
  public readonly upshiftAdvisor: UpshiftAdvisor;
  public readonly suspension: SuspensionSystem;
  public readonly wheelRotation: WheelRotationSystem;
  public readonly differential: OpenDifferential;
  public readonly transmission: TransmissionSystem;
  public readonly drivetrainLash: DrivetrainLash;

  public x = 0;
  public z = 0;
  public yaw = 0;
  /** Signed longitudinal velocity in m/s; negative means reversing. */
  public speed = 0;
  public acceleration = 0;
  public yawRate = 0;
  /** Positive means the velocity vector points to the vehicle's right. */
  public bodySlipAngle = 0;
  public lateralVelocity = 0;
  public lateralAcceleration = 0;
  public rearLateralGripFactor = 1;

  private forces: VehicleForceSnapshot = { ...ZERO_FORCES };
  private previousShiftUp = false;
  private previousShiftDown = false;
  private controlMode: VehicleControlMode = 'normal';
  private clutchPedal = 1;
  private shiftRejected = false;
  private shiftRejectionReason: ShiftRejectionReason | null = null;
  private shiftEventSequence = 0;
  private lastValidState: ValidCoreState;
  private recoveredThisUpdate = false;
  private wheels = {} as Record<WheelId, WheelPhysicsState>;
  /** Preserve an oblique collision's tangent velocity while contact settles. */
  private contactSlipRecovery = false;
  private contactSlipHoldTime = 0;

  public constructor(
    public readonly config: VehiclePhysicsConfig = createDefaultVehiclePhysicsConfig(),
    initialState: VehicleInitialState = {},
  ) {
    if (config.drivetrainType === 'AWD') throw new Error('AWD drivetrain is not implemented; select FWD or RWD.');
    this.differential = new OpenDifferential(config.drivetrainType === 'RWD' ? 'rear' : 'front');
    this.engine = new Engine(config.engine);
    this.clutch = new Clutch(config.clutch);
    this.autoClutch = new AutoClutchController(config.autoClutch, config.engine.idleRPM);
    this.gearbox = new Gearbox(config.transmission);
    this.transmission = createTransmissionSystem(config.transmission, this.gearbox, this.clutch, this.autoClutch, config.wheelRadius);
    this.drivetrainLash = new DrivetrainLash(this.transmission.type === 'MANUAL' ? config.transmission.drivetrainLash : undefined);
    this.brakes = new BrakeSystem(config.brakes, config.wheelRadius);
    this.driverAssists = new DriverAssistSystem(config);
    this.steering = new SteeringSystem(
      config.steering,
      config.wheelBase,
      config.frontTrackWidth,
    );
    this.upshiftAdvisor = new UpshiftAdvisor(
      config.engine.shiftRecommendation,
      this.gearbox.getMaximumForwardGear(),
    );
    this.suspension = new SuspensionSystem(config);
    this.wheelRotation = new WheelRotationSystem(config.tires, config.wheelRadius);
    this.lastValidState = {
      x: 0,
      z: 0,
      yaw: 0,
      speed: 0,
      rpm: config.engine.idleRPM,
      engineRunning: true,
      gear: 'N',
      clutchEngagement: 0,
      controlMode: 'normal',
      bodySlipAngle: 0,
      lateralVelocity: 0,
      contactSlipRecovery: false,
      contactSlipHoldTime: 0,
      yawRate: 0,
    };
    this.reset(initialState);
  }

  public reset(initialState: VehicleInitialState = {}): VehicleSnapshot {
    this.x = this.finiteOr(initialState.x, 0);
    this.z = this.finiteOr(initialState.z, 0);
    this.yaw = wrapAngle(this.finiteOr(initialState.yaw, 0));
    this.speed = clamp(
      this.finiteOr(initialState.speed, 0),
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );
    this.acceleration = 0;
    this.yawRate = 0;
    this.bodySlipAngle = 0;
    this.lateralVelocity = 0;
    this.contactSlipRecovery = false;
    this.contactSlipHoldTime = 0;
    this.lateralAcceleration = 0;
    this.rearLateralGripFactor = 1;
    this.suspension.reset();
    this.wheelRotation.reset(this.speed);
    this.differential.distributeTorque(0);
    this.initializeWheelStates();
    this.engine.reset(
      this.finiteOr(initialState.engineRPM, this.config.engine.idleRPM),
      initialState.engineRunning !== false,
    );
    this.driverAssists.reset(this.engine.isRunning);
    this.engine.setTorqueLimitFactor(1);
    this.gearbox.reset(initialState.gear ?? 'N');
    const initialEngagement = this.safeUnitInput(initialState.clutchEngagement ?? 0);
    this.clutch.reset(initialEngagement);
    this.autoClutch.reset(initialEngagement);
    this.transmission.reset(initialState.gear ?? 'N', initialState.driveSelector);
    this.drivetrainLash.reset();
    this.brakes.reset();
    this.steering.reset();
    this.upshiftAdvisor.reset();
    this.controlMode = this.transmission.type === 'MANUAL' && initialState.controlMode === 'manual-clutch'
      ? 'manual-clutch'
      : 'normal';
    this.clutchPedal = 1 - initialEngagement;
    this.forces = { ...ZERO_FORCES };
    this.previousShiftUp = false;
    this.previousShiftDown = false;
    this.shiftRejected = false;
    this.shiftRejectionReason = null;
    this.shiftEventSequence = 0;
    this.recoveredThisUpdate = false;
    this.storeLastValidState();
    this.updateUpshiftRecommendation();
    return this.getSnapshot();
  }

  public setPose(x: number, z: number, yaw: number, speed = this.speed): void {
    if (![x, z, yaw, speed].every(Number.isFinite)) return;
    this.x = x;
    this.z = z;
    this.yaw = wrapAngle(yaw);
    this.speed = clamp(
      speed,
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );
    this.wheelRotation.reset(this.speed);
    this.differential.distributeTorque(0);
    this.initializeWheelStates();
    this.storeLastValidState();
  }

  /**
   * Import a collision correction without retaining the pre-impact slip state.
   * CollisionSystem owns contact detection and response; this method only keeps
   * the drivetrain's local velocity and body/velocity heading consistent.
   */
  public applyContactCorrection(correction: VehicleContactCorrection): VehicleSnapshot {
    if (![correction.x, correction.z, correction.velocityX, correction.velocityZ]
      .every(Number.isFinite)) return this.getSnapshot();
    this.x = correction.x;
    this.z = correction.z;
    const sin = Math.sin(this.yaw);
    const cos = Math.cos(this.yaw);
    this.speed = clamp(
      -sin * correction.velocityX - cos * correction.velocityZ,
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );
    const lateral = cos * correction.velocityX - sin * correction.velocityZ;
    // At rest, retain a modest tangent drift rather than dividing by near-zero
    // forward speed. The normal driving solver damps it out progressively.
    this.lateralVelocity = lateral;
    this.bodySlipAngle = Math.abs(this.speed) > 0.05
      ? Math.atan(lateral / this.speed) : 0;
    this.contactSlipRecovery = Math.abs(lateral) > 0.025;
    // Repeated wall contacts refresh this short hold. A normal tyre-slip clamp
    // or its normal recovery must not turn an already corrected wall-tangent
    // velocity into inward motion again on the next 120 Hz step.
    this.contactSlipHoldTime = this.contactSlipRecovery ? 0.12 : 0;
    this.yawRate = clamp(
      this.finiteOr(correction.yawRate, 0),
      -this.config.steering.maximumYawRate,
      this.config.steering.maximumYawRate,
    );
    this.acceleration = 0;
    this.lateralAcceleration = -this.speed * this.yawRate;
    // An impact is an explicit velocity constraint. Remove stored wheel spin
    // energy with it so tyres cannot immediately shove the car into the wall.
    this.constrainWheelRotation(this.speed);
    this.storeLastValidState();
    return this.getSnapshot();
  }

  /**
   * Attempts to crank the engine. Starting in gear is permitted only when the
   * physical clutch is already sufficiently open, so callers can give useful
   * feedback without knowing any drivetrain internals.
   */
  public requestEngineStart(): boolean {
    if (this.engine.isRunning) return false;
    const automaticMode = this.transmission.getSnapshot().selectedMode;
    const drivetrainIsSafe = this.transmission.type !== 'MANUAL'
      ? automaticMode === 'P' || automaticMode === 'N'
      :
      this.gearbox.currentGear === 'N' ||
      1 - this.clutch.engagement >=
        this.config.transmission.minimumClutchDisengagementForShift;
    if (!drivetrainIsSafe) return false;
    this.engine.start();
    this.storeLastValidState();
    return true;
  }

  /**
   * Switches ignition off immediately. This is deliberately permitted while
   * moving or in gear; the drivetrain continues to coast/back-drive through
   * the normal clutch model and no pose or velocity state is rewritten.
   */
  public requestEngineStop(): boolean {
    if (!this.engine.isRunning) return false;
    this.engine.stop();
    this.updateUpshiftRecommendation();
    this.storeLastValidState();
    return true;
  }

  /** One edge-triggered cockpit command can safely operate both directions. */
  public requestEngineToggle(): EngineToggleResult {
    if (this.engine.isRunning) {
      this.requestEngineStop();
      return 'stopped';
    }
    return this.requestEngineStart() ? 'started' : 'start-rejected';
  }

  /**
   * Request a gear under the active control mode. Normal mode sequences the
   * automatic clutch; Manual mode swaps immediately only when actually open.
   */
  public requestGear(
    requestedGear: Gear,
    mode: VehicleControlMode = this.controlMode,
  ): boolean {
    if (this.transmission.type !== 'MANUAL') return this.rejectShift('gear-not-available');
    if (!this.gearbox.isGearAvailable(requestedGear)) {
      return this.rejectShift('gear-not-available');
    }
    let targetGear = requestedGear;
    const directionConflict =
      (requestedGear === 'R' && this.speed > this.config.transmission.reverseLockoutSpeed) ||
      (Gearbox.isForwardGear(requestedGear) &&
        this.speed < -this.config.transmission.reverseLockoutSpeed);
    if (directionConflict) targetGear = 'N';

    if (targetGear !== 'N' && this.wouldOverRev(targetGear)) {
      return this.rejectShift('engine-over-speed');
    }

    if (targetGear === this.gearbox.currentGear && this.autoClutch.pendingGear === null) {
      return this.rejectShift('already-selected');
    }

    if (mode === 'manual-clutch') {
      if (
        1 - this.clutch.engagement <
        this.config.transmission.minimumClutchDisengagementForShift
      ) {
        return this.rejectShift('clutch-not-disengaged');
      }
      this.gearbox.setGear(targetGear);
      this.acceptShift();
      return true;
    }

    if (!this.autoClutch.requestShift(targetGear)) {
      return this.rejectShift('shift-in-progress');
    }
    this.acceptShift();
    return true;
  }

  /** PRND uses the safety gate only; it never advances time or reads a device. */
  public requestDriveSelector(selector: DriveSelector, brake = this.brakes.brakeInput): boolean {
    return this.transmission.requestSelector(selector, this.speed, this.lateralVelocity, this.safeUnitInput(brake));
  }

  /** Variable-frame entry point with bounded internal substeps. */
  public update(
    deltaTime: number,
    input: VehicleInputState,
    environment: VehicleEnvironment = {},
  ): VehicleSnapshot {
    this.recoveredThisUpdate = false;
    this.validateOrRecover();
    this.updateControlMode(input.controlMode);
    this.processShiftCommands(input);

    if (!Number.isFinite(deltaTime) || deltaTime <= 0) return this.getSnapshot();
    const maxFrameTime = Math.max(1e-4, this.config.safety.maxFrameTime);
    const maxSubstep = Math.max(1e-4, this.config.safety.maxSubstep);
    const frameTime = Math.min(deltaTime, maxFrameTime);
    const stepCount = Math.max(1, Math.ceil(frameTime / maxSubstep));
    const dt = frameTime / stepCount;

    for (let step = 0; step < stepCount; step += 1) {
      this.integrateStep(dt, input, environment);
    }
    return this.getSnapshot();
  }

  /** Single integration step for tests or an upper-layer fixed-step driver. */
  public stepFixed(
    dt: number,
    input: VehicleInputState,
    environment: VehicleEnvironment = {},
  ): VehicleSnapshot {
    this.recoveredThisUpdate = false;
    this.validateOrRecover();
    this.updateControlMode(input.controlMode);
    this.processShiftCommands(input);
    if (Number.isFinite(dt) && dt > 0) {
      const maxFrameTime = Math.max(1e-4, this.config.safety.maxFrameTime);
      this.integrateStep(Math.min(dt, maxFrameTime), input, environment);
    }
    return this.getSnapshot();
  }

  public getSnapshot(): VehicleSnapshot {
    this.synchronizeWheelPositions();
    const upshift = this.upshiftAdvisor.getSample();
    const transmission = this.transmission.getSnapshot();
    const automaticEngagement = transmission.dct === undefined ? 0 :
      transmission.dct.clutchAEngagement + transmission.dct.clutchBEngagement;
    return {
      x: this.x,
      z: this.z,
      yaw: this.yaw,
      speed: this.speed,
      speedKmh: Math.abs(this.speed) * 3.6,
      acceleration: this.acceleration,
      yawRate: this.yawRate,
      bodySlipAngle: this.bodySlipAngle,
      lateralVelocity: this.lateralVelocity,
      lateralAcceleration: this.lateralAcceleration,
      rearLateralGripFactor: this.rearLateralGripFactor,
      rpm: this.engine.currentRPM,
      engineRunning: this.engine.isRunning,
      idleRPM: this.config.engine.idleRPM,
      shiftWarningRPM: upshift.targetRPM,
      recommendedUpshiftRPM: upshift.targetRPM,
      upshiftRecommendationAvailable: upshift.available,
      upshiftRecommended: upshift.recommended,
      redlineWarningRPM: this.config.engine.redlineWarningRPM,
      nearRedline: this.engine.currentRPM >= this.config.engine.redlineWarningRPM,
      onRevLimiter: this.engine.isOnLimiter,
      redlineRPM: this.config.engine.redlineRPM,
      gear: this.gearbox.currentGear,
      requestedGear: this.autoClutch.pendingGear,
      throttle: this.engine.throttle,
      brake: this.brakes.brakeInput,
      handbrake: this.brakes.handbrakeInput,
      steer: this.steering.steeringInput,
      controlMode: this.controlMode,
      clutchPedal: this.transmission.type !== 'MANUAL' ? 1 - automaticEngagement : this.controlMode === 'manual-clutch'
        ? this.clutchPedal
        : 1 - this.clutch.engagement,
      clutchEngagement: this.transmission.type === 'MANUAL' ? this.clutch.engagement : automaticEngagement,
      clutchState: this.clutch.state,
      autoClutchState: this.autoClutch.state,
      shiftRejected: this.shiftRejected,
      shiftRejectionReason: this.shiftRejectionReason,
      shiftEventSequence: this.shiftEventSequence,
      steeringAngle: this.steering.steeringAngle,
      leftRoadWheelAngle: this.steering.leftRoadWheelAngle,
      rightRoadWheelAngle: this.steering.rightRoadWheelAngle,
      steeringWheelAngle: this.steering.steeringWheelAngle,
      forces: { ...this.forces },
      wheels: Object.fromEntries(WHEEL_IDS.map((id) => [id, {
        ...this.wheels[id], worldPosition: { ...this.wheels[id].worldPosition },
        groundNormal: { ...this.wheels[id].groundNormal },
      }])) as Record<WheelId, WheelPhysicsState>,
      chassis: this.suspension.getSnapshot().chassis,
      transmission,
      drivetrainLash: this.drivetrainLash.getSnapshot(),
      revHang: this.engine.getRevHangSnapshot(),
      differential: this.getDifferentialSnapshot(),
      driverAssists: this.driverAssists.getSnapshot(),
      recoveredFromInvalidState: this.recoveredThisUpdate,
    };
  }

  private integrateStep(
    dt: number,
    input: VehicleInputState,
    environment: VehicleEnvironment,
  ): void {
    const throttleCommand = this.safeUnitInput(input.throttle);
    const brakeCommand = this.safeUnitInput(input.brake);
    const handbrakeCommand = this.safeUnitInput(input.handbrake);
    const steerCommand = clamp(this.finiteOr(input.steering, 0), -1, 1);

    let clutchTarget = 0;
    let autoUpdate: AutoClutchUpdateResult = {
      targetEngagement: this.clutch.engagement,
      cutThrottle: false,
    };
    const isManual = this.transmission.type === 'MANUAL';
    this.driverAssists.updateTraction(dt, this.wheels, throttleCommand, this.engine.isRunning,
      this.gearbox.currentGear !== 'N');
    this.engine.setTorqueLimitFactor(this.driverAssists.engineTorqueFactor);
    let automaticThrottleScale = 1;
    if (!isManual) {
      automaticThrottleScale = this.transmission.prepare({
        ...this.getTransmissionContext(dt, throttleCommand, brakeCommand), selectorRequest: input.driveSelector,
      }).throttleScale;
    } else if (this.controlMode === 'normal') {
      autoUpdate = this.autoClutch.update(dt, {
        currentEngagement: this.clutch.engagement,
        currentGear: this.gearbox.currentGear,
        vehicleSpeed: this.speed,
        engineRPM: this.engine.currentRPM,
        coupledEngineRPM: this.gearbox.getCoupledEngineRPM(
          this.speed,
          this.config.wheelRadius,
        ),
        throttle: throttleCommand,
      });
      if (autoUpdate.gearToEngage !== undefined) {
        this.gearbox.setGear(autoUpdate.gearToEngage);
      }
      clutchTarget = autoUpdate.targetEngagement;
    } else {
      this.clutchPedal = this.safeUnitInput(input.clutchPedal);
      clutchTarget = this.clutch.pedalToEngagement(this.clutchPedal);
    }

    if (isManual) this.clutch.update(dt, clutchTarget);
    this.engine.updateThrottle(autoUpdate.cutThrottle ? 0 : throttleCommand * automaticThrottleScale, dt, {
      enabled: isManual,
      gearEngaged: this.gearbox.currentGear !== 'N',
      clutchEngagement: this.clutch.engagement,
    });
    this.brakes.update(dt, brakeCommand, handbrakeCommand);
    const frontSurfaceGrip = environment.wheelContacts === undefined ?
      Math.max(0, this.finiteOr(environment.surfaceLateralGripMultiplier,
        this.finiteOr(environment.surfaceGripMultiplier, 1))) :
      (environment.wheelContacts.frontLeft.lateralGrip + environment.wheelContacts.frontRight.lateralGrip) * 0.5;
    this.steering.update(dt, steerCommand, this.speed, frontSurfaceGrip);
    const transmissionOutput = this.transmission.update(this.getTransmissionContext(dt, throttleCommand, brakeCommand));
    const clutchTorque = transmissionOutput.engineLoadTorque;
    const lashFactor = this.drivetrainLash.update(dt, transmissionOutput.transmittedTorque,
      this.config.clutch.maxClutchTorque);
    this.engine.integrate(dt, clutchTorque);

    const dragForce =
      -0.5 *
      this.config.aero.airDensity *
      this.config.aero.dragCoefficient *
      this.config.aero.frontalArea *
      this.speed *
      Math.abs(this.speed);
    const grade = this.getContactGrade(environment);
    const gradeForce = -this.config.mass * this.config.gravity * Math.sin(grade);
    const externalForce = this.finiteOr(environment.externalLongitudinalForce, 0);
    const tyreForces = this.calculateTyreContactForces(
      dt,
      environment,
      grade,
      transmissionOutput.drivenWheelTorque * lashFactor,
      dragForce + gradeForce + externalForce,
    );
    const {
      wheelForce,
      rollingForce,
      rollingMagnitude,
      serviceBrakeForce,
      handbrakeForce,
    } = tyreForces;
    const forceWithoutBrakes =
      wheelForce + dragForce + rollingForce + gradeForce + externalForce;
    const brakeForce = serviceBrakeForce + handbrakeForce;
    const netForce = forceWithoutBrakes + brakeForce;

    this.acceleration = netForce / Math.max(1, this.config.mass) -
      this.lateralVelocity * this.yawRate;
    const previousSpeed = this.speed;
    let nextSpeed = previousSpeed + this.acceleration * dt;

    // Passive resistance and either brake must not numerically push through zero.
    const crossedZero =
      (previousSpeed > 0 && nextSpeed < 0) || (previousSpeed < 0 && nextSpeed > 0);
    const propulsionWouldReverse = Math.abs(wheelForce + gradeForce + externalForce) <
      Math.abs(dragForce + rollingForce + brakeForce);
    if (crossedZero && propulsionWouldReverse) nextSpeed = 0;
    if (Math.abs(nextSpeed) < 0.002 && Math.abs(netForce) < rollingMagnitude + 1) nextSpeed = 0;
    // Only remove numerical residue at rest; normal braking is tyre slip/force.
    if (this.brakes.brakeInput > 0.1 && Math.abs(nextSpeed) < 0.003 &&
      Math.abs(netForce) < this.config.mass * 0.1) nextSpeed = 0;
    if (tyreForces.staticSupported) nextSpeed = 0;
    this.speed = clamp(
      nextSpeed,
      -this.config.safety.maxReverseSpeed,
      this.config.safety.maxForwardSpeed,
    );

    if (transmissionOutput.parkingLocked) {
      // A near-rest parking pawl is a velocity constraint, not an enormous
      // artificial braking force. It also holds gravity on a slope.
      this.speed = 0; this.acceleration = 0; this.lateralVelocity = 0; this.yawRate = 0;
      this.bodySlipAngle = 0; this.contactSlipRecovery = false; this.contactSlipHoldTime = 0;
      this.constrainWheelRotation(0);
    }
    if (tyreForces.staticSupported) {
      this.lateralVelocity = 0; this.yawRate = 0; this.bodySlipAngle = 0;
      this.contactSlipRecovery = false; this.contactSlipHoldTime = 0;
    }

    const averageSpeed = transmissionOutput.parkingLocked ? 0 : (previousSpeed + this.speed) * 0.5;
    if (!transmissionOutput.parkingLocked && !tyreForces.staticSupported) this.integrateLateralDynamics(dt, averageSpeed, tyreForces);
    else this.lateralAcceleration = 0;

    const engineBrakingForce =
      Math.abs(this.speed) > 0.05 && tyreForces.powertrainForce * this.speed < 0 && throttleCommand < 0.05
        ? tyreForces.powertrainForce
        : 0;
    this.forces = {
      wheelForce,
      brakeForce,
      serviceBrakeForce,
      handbrakeForce,
      aerodynamicDragForce: dragForce,
      rollingResistanceForce: rollingForce,
      gradeForce,
      externalForce,
      netForce,
      engineBrakingForce,
      clutchTorque,
      clutchSlipAngularVelocity: isManual ? this.clutch.lastSlipAngularVelocity :
        (this.engine.currentRPM - this.transmission.getSnapshot().inputRPM) * 2 * Math.PI / 60,
    };

    this.applyWorldBounds(environment.bounds);
    this.validateOrRecover();
    this.updateUpshiftRecommendation();
  }

  /** Sum four independently limited contact forces and moments in body coordinates. */
  private integrateLateralDynamics(
    dt: number,
    averageSpeed: number,
    contacts: TyreContactForces,
  ): void {
    const absoluteSpeed = Math.abs(averageSpeed);
    const collisionHold = this.contactSlipRecovery && this.contactSlipHoldTime > 0;
    if (collisionHold) {
      this.contactSlipHoldTime = Math.max(0, this.contactSlipHoldTime - dt);
    } else {
      // A small, dissipative contact relaxation damps sustained saturated
      // slides. It never adds yaw or changes the requested steering angle.
      // Grip loss weakens this damping naturally; restored rear grip lets a
      // released parking-brake slide settle instead of continuing to spin.
      const yawDamping = this.config.tires.lateralSlipRecoveryRate * 0.18 *
        Math.min(1, absoluteSpeed / 3) * this.rearLateralGripFactor;
      const yawAcceleration = contacts.yawMoment / Math.max(1, this.config.yawInertia) *
        Math.max(0.05, this.config.steering.yawResponseScale) - this.yawRate * yawDamping;
      this.yawRate += clamp(yawAcceleration, -5, 5) * dt;
      const maximumYawRate = Math.max(0.1, this.config.steering.maximumYawRate);
      this.yawRate = clamp(this.yawRate, -maximumYawRate, maximumYawRate);
      const lateralAcceleration = contacts.lateralForce / Math.max(1, this.config.mass) + averageSpeed * this.yawRate;
      this.lateralVelocity += lateralAcceleration * dt;
      if (absoluteSpeed < 0.4) {
        const restBlend = clamp01(1 - absoluteSpeed / 0.4);
        this.yawRate *= Math.exp(-12 * restBlend * dt);
        this.lateralVelocity *= Math.exp(-12 * restBlend * dt);
      }
      const slipLimit = Math.max(0.05, this.config.tires.maximumBodySlipAngle) * (averageSpeed < 0 ? 0.55 : 1);
      const velocityLimit = Math.max(0.05, absoluteSpeed) * Math.tan(slipLimit);
      if (!this.contactSlipRecovery) this.lateralVelocity = clamp(this.lateralVelocity, -velocityLimit, velocityLimit);
      if (this.contactSlipRecovery && Math.abs(this.lateralVelocity) < 0.025) this.contactSlipRecovery = false;
    }
    this.bodySlipAngle = absoluteSpeed > 0.05 ? Math.atan(this.lateralVelocity / averageSpeed) : 0;
    const middleYaw = this.yaw + this.yawRate * dt * 0.5;
    this.x += (-Math.sin(middleYaw) * averageSpeed +
      Math.cos(middleYaw) * this.lateralVelocity) * dt;
    this.z += (-Math.cos(middleYaw) * averageSpeed -
      Math.sin(middleYaw) * this.lateralVelocity) * dt;
    this.yaw = wrapAngle(this.yaw + this.yawRate * dt);
    this.lateralAcceleration = contacts.lateralForce / Math.max(1, this.config.mass);
  }

  /** Refresh contact metadata after the scene adapter's final pose/collision query. */
  public syncWheelContacts(contacts: WheelContactSet): void {
    this.suspension.synchronizeGroundGeometry(contacts);
    for (const id of WHEEL_IDS) {
      this.wheels[id] = {
        ...this.wheels[id],
        worldPosition: { x: contacts[id].x, y: contacts[id].height + this.config.wheelRadius, z: contacts[id].z },
        surfaceType: contacts[id].surfaceType,
        groundNormal: { ...contacts[id].normal },
      };
    }
  }

  private synchronizeWheelPositions(): void {
    for (const id of WHEEL_IDS) {
      const local = wheelLocalPosition(this.config, id);
      this.wheels[id] = {
        ...this.wheels[id],
        worldPosition: {
          x: this.x + local.x * Math.cos(this.yaw) + local.z * Math.sin(this.yaw),
          y: this.wheels[id].worldPosition.y,
          z: this.z - local.x * Math.sin(this.yaw) + local.z * Math.cos(this.yaw),
        },
      };
    }
  }

  /** Contact normals provide longitudinal slope, including heading across a ramp. */
  private getContactGrade(environment: VehicleEnvironment): number {
    const contacts = environment.wheelContacts;
    const normals = contacts === undefined
      ? (environment.groundNormal === undefined ? [] : [environment.groundNormal])
      : [contacts.frontLeft.normal, contacts.frontRight.normal,
        contacts.rearLeft.normal, contacts.rearRight.normal];
    if (normals.length === 0) return clamp(
      this.finiteOr(environment.gradeRadians, 0), -Math.PI * 0.45, Math.PI * 0.45,
    );
    let x = 0;
    let y = 0;
    let z = 0;
    for (const normal of normals) {
      x += this.finiteOr(normal.x, 0);
      y += Math.max(0, this.finiteOr(normal.y, 1));
      z += this.finiteOr(normal.z, 0);
    }
    // dy/ds = -(normal dot forward) / normal.y, forward=(-sin yaw,-cos yaw).
    return clamp(Math.atan2(x * Math.sin(this.yaw) + z * Math.cos(this.yaw),
      Math.max(1e-4, y)), -Math.PI * 0.45, Math.PI * 0.45);
  }

  /**
   * Static axle load is divided across four contacts. Each tyre gets its own
   * drive, brake and resistance budget, so straddling a boundary changes only
   * the contacting side instead of switching the entire car's material.
   */
  private calculateTyreContactForces(
    dt: number,
    environment: VehicleEnvironment,
    grade: number,
    requestedDriveTorque: number,
    otherLongitudinalForce: number,
  ): TyreContactForces {
    const suspension = this.suspension.update(dt, {
      contacts: environment.wheelContacts,
      normal: environment.groundNormal ?? { x: 0, y: Math.cos(grade), z: Math.sin(grade) },
      // Coordinate-speed derivative also contains -v_lateral*yawRate; load
      // transfer must use the actual body-forward force acceleration instead.
      longitudinalAcceleration: this.forces.netForce / Math.max(1, this.config.mass),
      lateralAcceleration: this.lateralAcceleration,
    });
    const frontWeight = clamp(this.config.frontWeightBias, 0.05, 0.95);
    const shares: FourWheelValues = [frontWeight * 0.5, frontWeight * 0.5,
      (1 - frontWeight) * 0.5, (1 - frontWeight) * 0.5];
    const localX: FourWheelValues = [-this.config.frontTrackWidth * 0.5,
      this.config.frontTrackWidth * 0.5, -this.config.rearTrackWidth * 0.5,
      this.config.rearTrackWidth * 0.5];
    const wheelContacts = environment.wheelContacts;
    const contacts = wheelContacts === undefined ? undefined : [
      wheelContacts.frontLeft, wheelContacts.frontRight,
      wheelContacts.rearLeft, wheelContacts.rearRight,
    ];
    const sharedGrip = Math.max(0, this.finiteOr(environment.surfaceGripMultiplier, 1));
    const legacyLongitudinal = sharedGrip * Math.max(0,
      this.finiteOr(environment.surfaceLongitudinalGripMultiplier, 1));
    const legacyLateral = sharedGrip * Math.max(0,
      this.finiteOr(environment.surfaceLateralGripMultiplier, 1));
    const legacyRolling = Math.max(0,
      this.finiteOr(environment.rollingResistanceMultiplier, 1));
    const gripLong = shares.map((_, i) => Math.max(0,
      this.finiteOr(contacts?.[i]?.longitudinalGrip, legacyLongitudinal))) as FourWheelValues;
    const gripLat = shares.map((_, i) => Math.max(0,
      this.finiteOr(contacts?.[i]?.lateralGrip, legacyLateral))) as FourWheelValues;
    const rolling = shares.map((_, i) => Math.max(0,
      this.finiteOr(contacts?.[i]?.rollingResistance, legacyRolling))) as FourWheelValues;
    const loads = WHEEL_IDS.map((id) => suspension.wheels[id].normalLoad) as FourWheelValues;
    const limits = loads.map((load, i) => this.config.tires.longitudinalGrip * load *
      this.wheelRotation.gripModel.loadFactor(load, suspension.wheels[WHEEL_IDS[i]!].staticLoad) * gripLong[i]!) as FourWheelValues;
    this.driverAssists.updateBrakes(dt, this.speed, this.brakes.brakeInput, this.wheels, limits);
    this.brakes.setDriverAidState(this.driverAssists.frontBrakeBias, this.driverAssists.pressures);
    // Transmission has already applied the final drive and efficiency. Only
    // the selected axle receives this torque; open side gears never bias grip.
    this.differential.distributeTorque(requestedDriveTorque);
    const requestedDrive: FourWheelValues = this.differential.axle === 'front'
      ? [this.differential.leftTorque, this.differential.rightTorque, 0, 0]
      : [0, 0, this.differential.leftTorque, this.differential.rightTorque];
    const rollingMagnitudes = loads.map((load, i) =>
      this.config.tires.rollingResistance * load * rolling[i]!) as FourWheelValues;
    const rollingForces = rollingMagnitudes.map((magnitude, i) =>
      -magnitude * Math.tanh((this.speed + this.yawRate * localX[i]!) / 0.2)) as FourWheelValues;
    const sum = (values: number[]): number => values.reduce((total, value) => total + value, 0);
    const usage: FourWheelValues = [0, 0, 0, 0];
    const lateral: FourWheelValues = [0, 0, 0, 0];
    const lateralLimits: FourWheelValues = [0, 0, 0, 0];
    const angles: FourWheelValues = [this.steering.leftRoadWheelAngle, this.steering.rightRoadWheelAngle, 0, 0];
    const brakeTorques = WHEEL_IDS.map(id => this.brakes.getWheelTorques(id));
    // A stopped tyre supports static shear on a hill even with zero slip.
    // Solve that dry-contact constraint only near rest and only within actual
    // brake torque AND tyre grip. Moving/locked-wheel braking keeps real slip.
    let staticForces: FourWheelValues | undefined;
    if (Math.hypot(this.speed, this.lateralVelocity) < 0.08 && Math.abs(this.yawRate) < 0.03 &&
      brakeTorques.some(b => b.appliedBrakeTorque + b.appliedHandbrakeTorque > 1) &&
      WHEEL_IDS.every(id => Math.abs(this.wheelRotation.getAngularVelocity(id) * this.config.wheelRadius) < 0.12)) {
      const minimum: FourWheelValues = [0, 0, 0, 0];
      const maximum: FourWheelValues = [0, 0, 0, 0];
      for (const i of [0, 1, 2, 3] as const) {
        const brake = brakeTorques[i]!;
        const capacity = brake.appliedBrakeTorque + brake.appliedHandbrakeTorque;
        const inertiaTorque = this.config.tires.wheelInertia *
          this.wheelRotation.getAngularVelocity(WHEEL_IDS[i]) / Math.max(1e-4, dt);
        const cosine = Math.cos(angles[i]);
        minimum[i] = Math.max(-limits[i], (requestedDrive[i] + inertiaTorque - capacity) /
          this.config.wheelRadius) * cosine;
        maximum[i] = Math.min(limits[i], (requestedDrive[i] + inertiaTorque + capacity) /
          this.config.wheelRadius) * cosine;
      }
      const required = -otherLongitudinalForce - sum(rollingForces.map((f, i) => f * Math.cos(angles[i]!))) -
        this.config.mass * this.speed / Math.max(1e-4, dt);
      const lower = sum(minimum); const upper = sum(maximum);
      if (minimum.every((v, i) => v <= maximum[i]!) && required >= lower && required <= upper) {
        const blend = upper - lower > 1e-6 ? (required - lower) / (upper - lower) : 0;
        staticForces = minimum.map((v, i) => (v + (maximum[i]! - v) * blend) /
          Math.cos(angles[i]!)) as FourWheelValues;
      }
    }
    const driveBody: FourWheelValues = [0, 0, 0, 0];
    const inertiaBody: FourWheelValues = [0, 0, 0, 0];
    const serviceBody: FourWheelValues = [0, 0, 0, 0];
    const handbrakeBody: FourWheelValues = [0, 0, 0, 0];
    const rollingBody: FourWheelValues = [0, 0, 0, 0];
    const lateralScrub: FourWheelValues = [0, 0, 0, 0];
    const rearAvailability: number[] = [];
    let asymmetricLongitudinalMoment = 0;
    let totalYawMoment = 0;
    const distanceToFront = clamp(this.config.wheelBase * (1 - frontWeight) -
      this.config.centerOfMassLongitudinalOffset, this.config.wheelBase * 0.1, this.config.wheelBase * 0.9);
    const distanceToRear = this.config.wheelBase - distanceToFront;
    const longitudinalPositions: FourWheelValues = [distanceToFront, distanceToFront, -distanceToRear, -distanceToRear];
    let staticSupported = staticForces !== undefined;
    for (const i of [0, 1, 2, 3] as const) {
      const id = WHEEL_IDS[i];
      const cosine = Math.cos(angles[i]);
      const sine = Math.sin(angles[i]);
      const wheelForwardVelocity = this.speed + this.yawRate * localX[i];
      const wheelLateralVelocity = this.lateralVelocity - this.yawRate * longitudinalPositions[i];
      const brake = brakeTorques[i]!;
      const handbrakeUsage = limits[i] > 1 ? clamp01(brake.appliedHandbrakeTorque / this.config.wheelRadius / limits[i]) : 0;
      const lockedRearAvailability = 1 - (1 - clamp01(this.config.tires.handbrakeRearGripFactor)) *
        handbrakeUsage * handbrakeUsage * (3 - 2 * handbrakeUsage);
      if (i >= 2) rearAvailability.push(lockedRearAvailability);
      const staticLoad = suspension.wheels[id].staticLoad;
      const loadStiffness = Math.max(0.1, loads[i] / Math.max(1, staticLoad));
      const corneringStiffness = (i < 2 ? this.config.tires.corneringStiffnessFront : this.config.tires.corneringStiffnessRear) * 0.5 * loadStiffness;
      const rotation = this.wheelRotation.updateWheel(id, dt, {
        longitudinalSpeed: wheelForwardVelocity * cosine + wheelLateralVelocity * sine,
        lateralSpeed: wheelLateralVelocity * cosine - wheelForwardVelocity * sine,
        driveTorque: requestedDrive[i], brakeTorque: brake.appliedBrakeTorque,
        handbrakeTorque: brake.appliedHandbrakeTorque, normalLoad: loads[i],
        surfaceLongitudinalGrip: gripLong[i],
        staticNormalLoad: staticLoad, surfaceLateralGrip: gripLat[i],
        corneringStiffness, lateralGripAvailability: lockedRearAvailability,
        staticLongitudinalForce: staticForces?.[i],
      });
      staticSupported = staticSupported && rotation.staticContact;
      const tyreForce = rotation.longitudinalForce;
      usage[i] = rotation.longitudinalUsage;
      lateralLimits[i] = rotation.lateralForceLimit;
      const slipAngle = rotation.slipAngle;
      const tyreLateral = rotation.lateralForce;
      // Torque-derived diagnostics close exactly with wheel inertia. Only the
      // actual slip-derived Fx enters the chassis: never sum the demands twice.
      const driveForce = requestedDrive[i] / this.config.wheelRadius;
      const serviceForce = -rotation.brakeReactionTorque / this.config.wheelRadius;
      const handbrakeForce = -rotation.handbrakeReactionTorque / this.config.wheelRadius;
      driveBody[i] = driveForce * cosine;
      inertiaBody[i] = rotation.rotationalInertiaForce * cosine;
      serviceBody[i] = serviceForce * cosine;
      handbrakeBody[i] = handbrakeForce * cosine;
      rollingBody[i] = rollingForces[i] * cosine;
      lateralScrub[i] = -tyreLateral * sine;
      const longitudinal = (tyreForce + rollingForces[i]) * cosine + lateralScrub[i];
      lateral[i] = (tyreForce + rollingForces[i]) * sine + tyreLateral * cosine;
      asymmetricLongitudinalMoment += localX[i] * (tyreForce + rollingForces[i]);
      totalYawMoment += localX[i] * longitudinal - longitudinalPositions[i] * lateral[i];
      const localWheel = wheelLocalPosition(this.config, id);
      const worldX = this.x + localWheel.x * Math.cos(this.yaw) + localWheel.z * Math.sin(this.yaw);
      const worldZ = this.z - localWheel.x * Math.sin(this.yaw) + localWheel.z * Math.cos(this.yaw);
      const spring = suspension.wheels[id];
      this.wheels[id] = {
        id,
        worldPosition: { x: contacts?.[i]?.x ?? worldX, y: (contacts?.[i]?.height ?? 0) + this.config.wheelRadius, z: contacts?.[i]?.z ?? worldZ },
        surfaceType: contacts?.[i]?.surfaceType ?? 'asphalt',
        groundNormal: { ...(contacts?.[i]?.normal ?? environment.groundNormal ?? { x: 0, y: Math.cos(grade), z: Math.sin(grade) }) },
        normalLoad: loads[i], steeringAngle: angles[i],
        driveTorque: requestedDrive[i], driveForce,
        brakeTorque: brake.appliedBrakeTorque, requestedBrakeTorque: brake.requestedBrakeTorque,
        appliedBrakeTorque: brake.appliedBrakeTorque, brakeForce: serviceForce,
        handbrakeTorque: brake.appliedHandbrakeTorque, requestedHandbrakeTorque: brake.requestedHandbrakeTorque,
        appliedHandbrakeTorque: brake.appliedHandbrakeTorque, handbrakeForce,
        rollingResistanceForce: rollingForces[i], longitudinalForce: tyreForce, lateralForce: tyreLateral,
        suspensionCompression: spring.compression, suspensionVelocity: spring.compressionVelocity,
        suspensionRestCompression: spring.restCompression, springForce: spring.springForce, damperForce: spring.damperForce,
        angularVelocity: rotation.angularVelocity, wheelAngularVelocity: rotation.angularVelocity,
        rotationAngle: rotation.rotationAngle, longitudinalSpeed: rotation.longitudinalSpeed,
        lateralSpeed: rotation.lateralSpeed, slipRatio: rotation.slipRatio, slipAngle,
        longitudinalUsage: rotation.longitudinalUsage, lateralUsage: rotation.lateralUsage, gripUsage: rotation.gripUsage,
      };
    }
    this.rearLateralGripFactor = rearAvailability.reduce((total, value) => total + value, 0) * 0.5;
    return {
      staticSupported,
      wheelForce: sum(driveBody) + sum(inertiaBody) + sum(lateralScrub),
      powertrainForce: sum(driveBody),
      serviceBrakeForce: sum(serviceBody),
      handbrakeForce: sum(handbrakeBody),
      rollingForce: sum(rollingBody),
      rollingMagnitude: sum(rollingMagnitudes),
      longitudinalForceLimit: sum(limits),
      frontLateralGrip: (gripLat[0] + gripLat[1]) * 0.5,
      rearLateralGrip: (gripLat[2] + gripLat[3]) * 0.5,
      frontLongitudinalUsage: (usage[0] + usage[1]) * 0.5,
      rearLongitudinalUsage: (usage[2] + usage[3]) * 0.5,
      contactYawAcceleration: clamp(asymmetricLongitudinalMoment / Math.max(1, this.config.yawInertia) *
        clamp01(this.config.tires.contactYawInfluence), -0.65, 0.65),
      lateralForce: sum(lateral),
      yawMoment: totalYawMoment,
      lateralForceLimit: sum(lateralLimits),
    };
  }

  private initializeWheelStates(): void {
    const springs = this.suspension.getSnapshot();
    for (const id of WHEEL_IDS) {
      const local = wheelLocalPosition(this.config, id);
      const spring = springs.wheels[id];
      const rotation = this.wheelRotation.getSnapshot(id);
      this.wheels[id] = {
        id, worldPosition: { x: this.x + local.x * Math.cos(this.yaw) + local.z * Math.sin(this.yaw), y: this.config.wheelRadius,
          z: this.z - local.x * Math.sin(this.yaw) + local.z * Math.cos(this.yaw) },
        surfaceType: 'asphalt', groundNormal: { x: 0, y: 1, z: 0 }, normalLoad: spring.normalLoad,
        steeringAngle: 0, driveTorque: 0, driveForce: 0, brakeTorque: 0, brakeForce: 0,
        requestedBrakeTorque: 0, appliedBrakeTorque: 0,
        handbrakeTorque: 0, handbrakeForce: 0, rollingResistanceForce: 0, longitudinalForce: 0, lateralForce: 0,
        requestedHandbrakeTorque: 0, appliedHandbrakeTorque: 0,
        suspensionCompression: spring.compression, suspensionVelocity: 0, suspensionRestCompression: spring.restCompression,
        springForce: spring.springForce, damperForce: 0,
        angularVelocity: rotation.angularVelocity, wheelAngularVelocity: rotation.angularVelocity,
        rotationAngle: rotation.rotationAngle, longitudinalSpeed: rotation.longitudinalSpeed,
        lateralSpeed: 0, slipRatio: 0, slipAngle: 0,
        longitudinalUsage: 0, lateralUsage: 0, gripUsage: 0,
      };
    }
  }

  /** Only a discontinuous contact/pawl constraint may synchronise wheel spin. */
  private constrainWheelRotation(speed: number): void {
    for (const id of WHEEL_IDS) {
      const local = wheelLocalPosition(this.config, id);
      const angle = this.wheels[id].steeringAngle;
      const forward = speed + this.yawRate * local.x;
      const side = this.lateralVelocity + this.yawRate * local.z;
      const longitudinalSpeed = forward * Math.cos(angle) + side * Math.sin(angle);
      const lateralSpeed = side * Math.cos(angle) - forward * Math.sin(angle);
      this.wheelRotation.constrainAngularVelocity(id, longitudinalSpeed / Math.max(0.01, this.config.wheelRadius),
        longitudinalSpeed, lateralSpeed);
      const rotation = this.wheelRotation.getSnapshot(id);
      this.wheels[id] = { ...this.wheels[id], angularVelocity: rotation.angularVelocity,
        wheelAngularVelocity: rotation.angularVelocity, rotationAngle: rotation.rotationAngle,
        longitudinalSpeed, lateralSpeed, slipRatio: rotation.slipRatio, slipAngle: rotation.slipAngle,
        longitudinalForce: 0, lateralForce: 0, driveForce: 0, brakeForce: 0, handbrakeForce: 0,
        rollingResistanceForce: 0, longitudinalUsage: 0, lateralUsage: 0, gripUsage: 0 };
    }
  }

  private getDrivenWheelAngularVelocity(): number {
    const front = this.differential.axle === 'front';
    return this.differential.updateSpeeds(
      this.wheelRotation.getAngularVelocity(front ? 'frontLeft' : 'rearLeft'),
      this.wheelRotation.getAngularVelocity(front ? 'frontRight' : 'rearRight'));
  }

  private getDifferentialSnapshot(): OpenDifferentialSnapshot {
    this.getDrivenWheelAngularVelocity();
    return this.differential.getSnapshot();
  }

  private updateControlMode(requestedMode: VehicleControlMode): void {
    if (this.transmission.type !== 'MANUAL') { this.controlMode = 'normal'; return; }
    const nextMode: VehicleControlMode = requestedMode === 'manual-clutch'
      ? 'manual-clutch'
      : 'normal';
    if (nextMode === this.controlMode) return;

    if (nextMode === 'manual-clutch') {
      this.autoClutch.releaseControl(this.clutch.engagement);
      // The input layer mirrors this value on R3; retaining it here makes the
      // physics transition continuous even if a custom adapter is one frame late.
      this.clutchPedal = 1 - this.clutch.engagement;
    } else {
      this.autoClutch.takeOver(this.clutch.engagement);
      this.clutchPedal = 1 - this.clutch.engagement;
    }
    this.controlMode = nextMode;
  }

  private processShiftCommands(input: VehicleInputState): void {
    const shiftUp = input.shiftUp === true;
    const shiftDown = input.shiftDown === true;
    if (this.transmission.type !== 'MANUAL') {
      // The same device-independent shift edges select PRND on automatics.
      // Stop at the ends: D must never wrap straight into P. Explicit selector
      // requests take priority and use the existing prepare/safety path.
      const direction = shiftUp && !this.previousShiftUp && !shiftDown ? 1
        : shiftDown && !this.previousShiftDown && !shiftUp ? -1 : 0;
      if (input.driveSelector === undefined && direction !== 0) {
        const selectors: readonly DriveSelector[] = ['P', 'R', 'N', 'D'];
        const current = this.transmission.getSnapshot().selectedMode ?? 'P';
        const next = selectors[selectors.indexOf(current) + direction];
        if (next !== undefined) this.requestDriveSelector(next, input.brake);
      }
    } else if (input.directGear !== undefined) {
      this.requestGear(input.directGear, this.controlMode);
    } else if (shiftUp && !this.previousShiftUp && !shiftDown) {
      this.requestGear(this.gearbox.getShiftUpGear(), this.controlMode);
    } else if (shiftDown && !this.previousShiftDown && !shiftUp) {
      this.requestGear(this.gearbox.getShiftDownGear(), this.controlMode);
    }
    this.previousShiftUp = shiftUp;
    this.previousShiftDown = shiftDown;
  }

  private wouldOverRev(targetGear: Exclude<Gear, 'N'>): boolean {
    const ratio = this.gearbox.getRatio(targetGear);
    const wheelAngularVelocity = this.speed / Math.max(0.01, this.config.wheelRadius);
    const coupledRPM = Math.abs(
      (wheelAngularVelocity * ratio * this.config.transmission.finalDriveRatio * 60) /
        (Math.PI * 2),
    );
    return coupledRPM > this.config.engine.maxRPM * 1.05;
  }

  private acceptShift(): void {
    this.shiftRejected = false;
    this.shiftRejectionReason = null;
    this.shiftEventSequence += 1;
  }

  private rejectShift(reason: ShiftRejectionReason): false {
    this.shiftRejected = true;
    this.shiftRejectionReason = reason;
    this.shiftEventSequence += 1;
    return false;
  }

  private applyWorldBounds(bounds: VehicleWorldBounds | undefined): void {
    if (bounds === undefined) return;
    if (![bounds.minX, bounds.maxX, bounds.minZ, bounds.maxZ].every(Number.isFinite)) return;
    if (bounds.minX > bounds.maxX || bounds.minZ > bounds.maxZ) return;
    const boundedX = clamp(this.x, bounds.minX, bounds.maxX);
    const boundedZ = clamp(this.z, bounds.minZ, bounds.maxZ);
    if (boundedX !== this.x || boundedZ !== this.z) {
      this.x = boundedX;
      this.z = boundedZ;
      this.speed = 0;
      this.acceleration = 0;
      this.yawRate = 0;
      this.bodySlipAngle = 0;
      this.lateralVelocity = 0;
      this.lateralAcceleration = 0;
      this.constrainWheelRotation(0);
    }
  }

  private validateOrRecover(): void {
    const values = [
      this.x,
      this.z,
      this.yaw,
      this.speed,
      this.acceleration,
      this.yawRate,
      this.bodySlipAngle,
      this.lateralVelocity,
      this.lateralAcceleration,
      this.rearLateralGripFactor,
      this.engine.currentRPM,
      this.clutch.engagement,
      this.clutch.targetEngagement,
      this.brakes.brakeInput,
      this.brakes.handbrakeInput,
      ...WHEEL_IDS.flatMap(id => [this.wheelRotation.getSnapshot(id).angularVelocity,
        this.wheelRotation.getSnapshot(id).rotationAngle, this.wheels[id].slipRatio]),
    ];
    const positionIsReasonable =
      Math.abs(this.x) <= this.config.safety.maxAbsPosition &&
      Math.abs(this.z) <= this.config.safety.maxAbsPosition;
    if (values.every(Number.isFinite) && positionIsReasonable) {
      this.storeLastValidState();
      return;
    }

    this.x = this.lastValidState.x;
    this.z = this.lastValidState.z;
    this.yaw = this.lastValidState.yaw;
    this.speed = this.lastValidState.speed;
    this.acceleration = 0;
    this.yawRate = this.lastValidState.yawRate;
    this.bodySlipAngle = this.lastValidState.bodySlipAngle;
    this.lateralVelocity = this.lastValidState.lateralVelocity;
    this.contactSlipRecovery = this.lastValidState.contactSlipRecovery;
    this.contactSlipHoldTime = this.lastValidState.contactSlipHoldTime;
    this.lateralAcceleration = -this.speed * this.yawRate;
    this.rearLateralGripFactor = 1;
    this.engine.reset(this.lastValidState.rpm, this.lastValidState.engineRunning);
    this.gearbox.reset(this.lastValidState.gear);
    this.transmission.reset(this.lastValidState.gear, this.lastValidState.driveSelector);
    this.drivetrainLash.reset();
    this.clutch.reset(this.lastValidState.clutchEngagement);
    this.controlMode = this.lastValidState.controlMode;
    this.clutchPedal = 1 - this.clutch.engagement;
    if (this.transmission.type === 'MANUAL' && this.controlMode === 'normal') {
      this.autoClutch.takeOver(this.clutch.engagement);
    } else if (this.transmission.type === 'MANUAL') {
      this.autoClutch.releaseControl(this.clutch.engagement);
    }
    this.brakes.reset();
    this.steering.reset();
    this.suspension.reset();
    this.wheelRotation.reset(this.speed);
    this.differential.distributeTorque(0);
    this.initializeWheelStates();
    this.upshiftAdvisor.reset();
    this.forces = { ...ZERO_FORCES };
    this.recoveredThisUpdate = true;
  }

  private storeLastValidState(): void {
    this.lastValidState = {
      x: this.x,
      z: this.z,
      yaw: this.yaw,
      speed: this.speed,
      rpm: this.engine.currentRPM,
      engineRunning: this.engine.isRunning,
      gear: this.gearbox.currentGear,
      clutchEngagement: this.clutch.engagement,
      controlMode: this.controlMode,
      bodySlipAngle: this.bodySlipAngle,
      lateralVelocity: this.lateralVelocity,
      contactSlipRecovery: this.contactSlipRecovery,
      contactSlipHoldTime: this.contactSlipHoldTime,
      yawRate: this.yawRate,
      driveSelector: this.transmission.getSnapshot().selectedMode ?? undefined,
    };
  }

  private safeUnitInput(value: number): number {
    return clamp01(this.finiteOr(value, 0));
  }

  private updateUpshiftRecommendation(): void {
    this.upshiftAdvisor.update({
      engineRPM: this.engine.currentRPM,
      throttle: this.engine.throttle,
      speedKmh: Math.abs(this.speed) * 3.6,
      gear: this.gearbox.currentGear,
      shiftInProgress: this.autoClutch.isShifting || this.transmission.type !== 'MANUAL',
    });
  }

  private finiteOr(value: number | undefined, fallback: number): number {
    return value !== undefined && Number.isFinite(value) ? value : fallback;
  }

  private getTransmissionContext(dt: number, throttle: number, brake: number): TransmissionContext {
    return { dt, engineAngularVelocity: this.engine.angularVelocity, engineRPM: this.engine.currentRPM,
      engineRunning: this.engine.isRunning, engineInertia: this.config.engine.engineInertia,
      idleRPM: this.config.engine.idleRPM, stallRPM: this.config.engine.stallRPM,
      redlineRPM: this.config.engine.redlineRPM, availableEngineTorque: this.engine.getTorqueSample().netCrankTorque,
      throttle, brake, vehicleSpeed: this.speed,
      vehicleLateralSpeed: this.lateralVelocity,
      drivenWheelAngularVelocity: this.getDrivenWheelAngularVelocity() };
  }
}
