import type { VehicleRuntimeSnapshot } from '../physics/VehicleDynamics';
import { DEFAULT_VEHICLE_PHYSICS_CONFIG, type ClutchConfig, type EngineConfig } from '../config';
import { clamp, damp } from '../physics/math';

export interface RumbleIntensity { readonly weak: number; readonly strong: number }
export interface HapticPulse extends RumbleIntensity {
  readonly kind: 'stall' | 'collision' | 'jolt';
  readonly durationMs: number;
}
export interface VehicleFeedbackConfig {
  /** Legacy setting retained for configuration compatibility; idle never drives gamepad rumble. */
  idleVibrationStrength: number;
  /** Weak-motor magnitude at maximum low-RPM drivetrain judder. */
  clutchJudderStrength: number;
  /** Near-stall uses a separate rougher, stronger layer than ordinary bite. */
  nearStallWeakStrength: number;
  nearStallStrongStrength: number;
  /** Peak weak-motor magnitude of a genuinely mismatched re-engagement. */
  shiftJoltStrength: number;
}
export const DEFAULT_VEHICLE_FEEDBACK_CONFIG: Readonly<VehicleFeedbackConfig> = {
  idleVibrationStrength: 0,
  clutchJudderStrength: 0.25,
  nearStallWeakStrength: 0.35,
  nearStallStrongStrength: 0.15,
  shiftJoltStrength: 0.12,
};
export interface VehicleFeedbackCalibration {
  readonly engine: Pick<EngineConfig, 'idleRPM' | 'stallRPM'>;
  readonly clutch: Pick<ClutchConfig, 'bitePointStart' | 'bitePointEnd' | 'maxClutchTorque'>;
}
export interface VehicleFeedbackContext {
  /** Optional signed mechanical impulse, -1..1; shares the existing jolt envelope. */
  readonly drivetrainLashJolt?: number;
}
export interface FeedbackCollisionSample {
  readonly collided: boolean;
  readonly contacts: readonly { readonly inwardSpeed: number }[];
}
type FeedbackSnapshotCore = Pick<VehicleRuntimeSnapshot, 'speed' | 'rpm' | 'idleRPM' | 'engineRunning'
  | 'gear' | 'throttle' | 'clutchEngagement' | 'acceleration' | 'forces'>;
/** Optional transmission data keeps this observer compatible with all drivetrain variants. */
export interface VehicleFeedbackSnapshot extends FeedbackSnapshotCore {
  readonly startStop?: VehicleRuntimeSnapshot['startStop'];
  readonly controlMode?: VehicleRuntimeSnapshot['controlMode'];
  readonly clutchPedal?: number;
  readonly transmission?: {
    readonly type?: string;
    readonly engineLoadTorque?: number;
    readonly dct?: { readonly clutchAEngagement: number; readonly clutchBEngagement: number };
  };
}
export interface VehicleFeedbackFactors {
  readonly partialClutchFactor: number;
  readonly slipFactor: number;
  /** Absolute transmitted torque / the vehicle's full clutch capacity. */
  readonly clutchLoad: number;
  readonly clutchLoadFactor: number;
  readonly lowRPMFactor: number;
  /** Mechanical stall risk, independent of the partial-clutch bell curve. */
  readonly nearStallFactor: number;
  readonly speedAttenuation: number;
  readonly autoClutchFeedbackScale: number;
  readonly judderTarget: number;
  readonly nearStallTarget: number;
}
export interface VehicleFeedbackState {
  readonly idleVibrationIntensity: number;
  readonly clutchJudderIntensity: number;
  readonly nearStallVibrationIntensity: number;
  /** Shared mechanical envelope for cockpit movement and gamepad feedback. */
  readonly drivetrainVibrationIntensity: number;
  readonly drivetrainJoltIntensity: number;
  /** SI metres, relative cockpit movement only. Never apply to vehicle/world/mirrors. */
  readonly cockpitOffset: { readonly x: number; readonly y: number; readonly z: number };
  readonly continuousRumble: RumbleIntensity;
  /** Read-only calibration diagnostics; intended for F2, not the normal HUD. */
  readonly factors: Readonly<VehicleFeedbackFactors>;
  /** Edge events generated by this update. Collect after every fixed physics step. */
  readonly hapticPulses: readonly HapticPulse[];
}

/**
 * Pure read-only drivetrain observer. No device API, force injection, scripted
 * shift animation or random shake; it cannot alter a snapshot or vehicle speed.
 */
export class VehicleFeedbackSystem {
  private readonly config: VehicleFeedbackConfig;
  private calibration: VehicleFeedbackCalibration = DEFAULT_VEHICLE_PHYSICS_CONFIG;
  private previous: { running: boolean; acceleration: number; torque: number; engagement: number } | null = null;
  private idlePhase = 0;
  private judderPhase = 0;
  private idle = 0;
  private judder = 0;
  private nearStall = 0;
  private jolt = 0;
  private joltDisplacement = 0;
  private joltVelocity = 0;
  private filteredAcceleration = 0;
  private joltArmed = true;
  private joltCooldown = 0;
  private previousLashMagnitude = 0;
  private collisionQuietTime = 1;
  private outputState: VehicleFeedbackState = emptyState();

  constructor(config: Partial<VehicleFeedbackConfig> = {}) {
    this.config = { ...DEFAULT_VEHICLE_FEEDBACK_CONFIG, ...config };
    for (const key of Object.keys(this.config) as (keyof VehicleFeedbackConfig)[]) {
      this.config[key] = clamp(finite(this.config[key]), 0, 1);
    }
    this.config.clutchJudderStrength = Math.min(this.config.clutchJudderStrength, 0.25);
    this.config.nearStallWeakStrength = Math.min(this.config.nearStallWeakStrength, 0.35);
    this.config.nearStallStrongStrength = Math.min(this.config.nearStallStrongStrength, 0.15);
    this.setVehicleConfig(DEFAULT_VEHICLE_PHYSICS_CONFIG);
  }

  get current(): Readonly<VehicleFeedbackState> { return this.outputState; }
  get state(): Readonly<VehicleFeedbackState> { return this.outputState; }

  /** Copy only calibration numbers; this observer never writes into vehicle config. */
  setVehicleConfig(config: VehicleFeedbackCalibration | import('../config').VehicleChassisConfig): void {
    if (!('engine' in config) || !('clutch' in config)) return;
    const idleRPM = Math.max(1, finite(config.engine.idleRPM, 850));
    const bitePointStart = clamp(finite(config.clutch.bitePointStart, 0.98), 0.0001, 1);
    this.calibration = {
      engine: { idleRPM, stallRPM: clamp(finite(config.engine.stallRPM, idleRPM * 0.58), 0, idleRPM - 0.0001) },
      clutch: {
        bitePointStart,
        bitePointEnd: clamp(finite(config.clutch.bitePointEnd, 0.02), 0, bitePointStart - 0.0001),
        maxClutchTorque: Math.max(1, finite(config.clutch.maxClutchTorque, 285)),
      },
    };
  }

  /** Rebase after spawn, vehicle/map switch, or an explicit ignition toggle. */
  reset(snapshot?: VehicleFeedbackSnapshot): void {
    this.previous = snapshot === undefined ? null : {
      running: snapshot.engineRunning === true, acceleration: finite(snapshot.acceleration),
      torque: this.loadTorque(snapshot), engagement: this.engagement(snapshot),
    };
    this.idlePhase = 0; this.judderPhase = 0; this.idle = 0; this.judder = 0; this.nearStall = 0; this.jolt = 0;
    this.joltDisplacement = 0; this.joltVelocity = 0;
    this.filteredAcceleration = snapshot === undefined ? 0 : finite(snapshot.acceleration);
    this.joltArmed = true; this.joltCooldown = 0; this.previousLashMagnitude = 0; this.collisionQuietTime = 1;
    this.outputState = emptyState();
  }

  update(dt: number, snapshot: VehicleFeedbackSnapshot, collision?: FeedbackCollisionSample | null,
    context?: VehicleFeedbackContext): Readonly<VehicleFeedbackState> {
    if (!Number.isFinite(dt) || dt <= 0) return this.outputState;
    const step = Math.min(dt, 0.05);
    const rpm = Math.max(0, finite(snapshot.rpm));
    const idleRPM = Math.max(1, finite(snapshot.idleRPM, this.calibration.engine.idleRPM));
    const stallRPM = Math.min(this.calibration.engine.stallRPM, idleRPM - 0.0001);
    const rpmSpan = Math.max(1, idleRPM - stallRPM);
    const speed = Math.abs(finite(snapshot.speed));
    const engagement = this.engagement(snapshot);
    const torque = this.loadTorque(snapshot);
    const acceleration = finite(snapshot.acceleration);
    const previous = this.previous;
    const type = snapshot.transmission?.type ?? 'MANUAL';
    const manual = type === 'MANUAL';
    const manualClutch = manual && snapshot.controlMode === 'manual-clutch';
    const dct = type === 'DCT';
    const pulses: HapticPulse[] = [];
    this.joltCooldown = Math.max(0, this.joltCooldown - step);
    const clutchReleased = engagement <= 0.02 || (manualClutch && finite(snapshot.clutchPedal) >= 0.98);
    const connected = snapshot.engineRunning && snapshot.gear !== 'N' && !clutchReleased;
    // Bite limits are pedal-down coordinates, just as in Clutch.getTorqueCapacity.
    const bite = this.calibration.clutch;
    const biteProgress = clamp((engagement - (1 - bite.bitePointStart))
      / (bite.bitePointStart - bite.bitePointEnd), 0, 1);
    const partialClutchFactor = smooth(0, 0.5, biteProgress) * (1 - smooth(0.5, 1, biteProgress));
    const slipRPM = Math.abs(finite(snapshot.forces.clutchSlipAngularVelocity)) * 60 / (2 * Math.PI);
    const slipFactor = smooth(idleRPM * 0.035, idleRPM * 0.6, slipRPM);
    const clutchLoad = clamp(Math.abs(torque) / bite.maxClutchTorque, 0, 1);
    const clutchLoadFactor = smooth(0.015, 0.45, clutchLoad);
    const normalizedRPM = (rpm - stallRPM) / rpmSpan;
    const lowRPMFactor = 1 - smooth(0, 2.5, normalizedRPM);
    const rpmStallRisk = 1 - smooth(0, 1, normalizedRPM);
    const nearStallFactor = connected ? rpmStallRisk * smooth(0.02, 0.25, clutchLoad)
      * smooth(0.02, 0.18, engagement) : 0;
    // Low speed never starts a vibration. This only fades an existing mechanical
    // judder above 18 km/h; standing still has exactly the same multiplier.
    const speedAttenuation = 1 - smooth(5, 18, speed);
    const autoClutchFeedbackScale = 0.12 * smooth(0.32, 0.7, clutchLoad)
      * smooth(0.15, 0.7, rpmStallRisk) * Math.max(slipFactor, rpmStallRisk);
    const modeScale = manualClutch ? 1 : manual || dct ? autoClutchFeedbackScale : 0;
    const judderTarget = connected ? smooth(0, 1, partialClutchFactor * slipFactor
      * clutchLoadFactor * lowRPMFactor) * speedAttenuation * modeScale : 0;
    const nearStallTarget = nearStallFactor * modeScale;
    const rpmIdleWeight = smooth(stallRPM, idleRPM - rpmSpan * 0.12, rpm)
      * (1 - smooth(idleRPM + rpmSpan * 0.2, idleRPM + rpmSpan * 1.2, rpm));
    const stable = (1 - smooth(0.1, 0.8, speed)) * (1 - smooth(0.25, 1.5, Math.abs(acceleration)));
    const idleTarget = snapshot.engineRunning ? rpmIdleWeight * stable
      * (1 - 0.45 * smooth(0.15, 0.65, snapshot.throttle)) : 0;
    const rapidRelease = !connected;
    this.idle = snapshot.engineRunning ? envelope(this.idle, idleTarget, 0.12, 0.08, step) : 0;
    this.judder = snapshot.engineRunning ? envelope(this.judder, judderTarget, 0.09, rapidRelease ? 0.035 : 0.16, step) : 0;
    this.nearStall = snapshot.engineRunning ? envelope(this.nearStall, nearStallTarget, 0.07, rapidRelease ? 0.035 : 0.12, step) : 0;
    if (snapshot.engineRunning) {
      this.idlePhase = (this.idlePhase + rpm / 60 * 2 * Math.PI * 2 * step) % (Math.PI * 2);
      this.judderPhase = (this.judderPhase + rpm / 60 * 0.45 * Math.PI * 2 * step) % (Math.PI * 2);
    }

    const previousFilteredAcceleration = this.filteredAcceleration;
    this.filteredAcceleration = damp(this.filteredAcceleration, acceleration, 18, step);
    const jerk = (this.filteredAcceleration - previousFilteredAcceleration) / step;
    const lashJolt = clamp(finite(context?.drivetrainLashJolt), -1, 1);
    const lashMagnitude = Math.abs(lashJolt);
    const lashOnset = lashMagnitude - this.previousLashMagnitude;
    let joltDemand = 0;
    if (previous !== null && snapshot.engineRunning && snapshot.gear !== 'N') {
      const closeRate = Math.max(0, (engagement - previous.engagement) / step);
      const torqueRate = (torque - previous.torque) / step;
      const mismatchRPM = Math.abs(finite(snapshot.forces.clutchSlipAngularVelocity)) * 60 / (2 * Math.PI);
      const mismatch = smooth(60, 1_000, mismatchRPM);
      // Keep the existing re-engagement jolt calibration separate from continuous load.
      const load = smooth(10, 90, Math.abs(torque));
      const engagementShock = smooth(0.1, 2.5, closeRate) * mismatch * load;
      const torqueShock = smooth(80, 900, Math.abs(torqueRate)) * smooth(2, 20, Math.abs(jerk)) * load;
      joltDemand = clamp(engagementShock * (0.4 + 0.6 * smooth(1, 14, Math.abs(jerk)))
        + torqueShock * (manual ? 0.25 : dct ? 0.2 : 0.1), 0, 1);
      if (joltDemand < 0.12) this.joltArmed = true;
      const reengagementEvent = joltDemand > 0.22;
      // Lash is a small measured reload impulse (normally <= .22), so its
      // onset can enter the same spring below the larger re-engagement gate.
      const lashEvent = lashMagnitude > 0.035 && lashOnset > 0.005 && clutchLoad >= 0.14;
      if ((reengagementEvent || lashEvent) && this.joltArmed && this.joltCooldown === 0) {
        this.joltArmed = false;
        this.joltCooldown = 0.22;
        const eventDemand = reengagementEvent ? joltDemand : lashMagnitude;
        const sign = Math.sign(reengagementEvent ? jerk || torqueRate || torque : lashJolt);
        this.joltVelocity = clamp(this.joltVelocity + sign * eventDemand * 0.07, -0.16, 0.16);
        pulses.push({ kind: 'jolt', weak: this.config.shiftJoltStrength * eventDemand,
          strong: this.config.shiftJoltStrength * eventDemand * 0.28, durationMs: 65 });
      }
      joltDemand = Math.max(joltDemand, lashMagnitude);
    }
    this.previousLashMagnitude = lashMagnitude;
    this.jolt = Math.max(joltDemand, this.jolt * Math.exp(-step * 14));
    const automaticStop = snapshot.startStop?.state === 'AUTO_STOPPED' || snapshot.startStop?.state === 'RESTARTING';
    if (previous?.running && !snapshot.engineRunning && !automaticStop) {
      pulses.push({ kind: 'stall', weak: 0.22, strong: 0.4, durationMs: 140 });
      this.joltVelocity -= 0.035;
    }
    if (collision?.collided) {
      const impact = Math.max(0, ...collision.contacts.map(contact => finite(contact.inwardSpeed)));
      if (this.collisionQuietTime >= 0.16 && impact > 0.15) {
        const severity = smooth(0.1, 12, impact);
        pulses.push({ kind: 'collision', weak: 0.1 + severity * 0.3,
          strong: 0.3 + severity * 0.6, durationMs: 75 + severity * 105 });
      }
      this.collisionQuietTime = 0;
    } else {
      this.collisionQuietTime += step;
    }

    // Exact critically damped spring; suspension already supplies body pitch.
    const frequency = 34;
    const springCoefficient = this.joltVelocity + frequency * this.joltDisplacement;
    const springDecay = Math.exp(-frequency * step);
    this.joltDisplacement = clamp((this.joltDisplacement + springCoefficient * step) * springDecay, -0.006, 0.006);
    this.joltVelocity = (this.joltVelocity - frequency * springCoefficient * step) * springDecay;
    const idleWave = Math.sin(this.idlePhase);
    const judderWave = Math.sin(this.judderPhase);
    const drivetrainVibrationIntensity = clamp(this.judder + this.nearStall, 0, 1);
    // Ordinary idle retains only a submillimetre visual cockpit motion, never gamepad rumble.
    const cockpitOffset = {
      x: this.idle * Math.sin(this.idlePhase * 0.5) * 0.00008,
      y: this.idle * idleWave * 0.00023 + drivetrainVibrationIntensity * judderWave * 0.0022,
      z: this.joltDisplacement + drivetrainVibrationIntensity * Math.sin(this.judderPhase + Math.PI / 3) * 0.0011,
    };
    const weak = this.judder * this.config.clutchJudderStrength * (0.9 + 0.1 * judderWave)
      + this.nearStall * this.config.nearStallWeakStrength * (0.8 + 0.2 * judderWave);
    this.outputState = {
      idleVibrationIntensity: this.idle, clutchJudderIntensity: this.judder,
      nearStallVibrationIntensity: this.nearStall, drivetrainVibrationIntensity,
      drivetrainJoltIntensity: this.jolt, cockpitOffset,
      continuousRumble: { weak: clamp(weak, 0, 0.35),
        strong: clamp(this.judder * 0.05 + this.nearStall * this.config.nearStallStrongStrength, 0, 0.15) },
      factors: { partialClutchFactor, slipFactor, clutchLoad, clutchLoadFactor, lowRPMFactor,
        nearStallFactor, speedAttenuation, autoClutchFeedbackScale, judderTarget, nearStallTarget },
      hapticPulses: pulses,
    };
    this.previous = { running: snapshot.engineRunning === true, acceleration, torque, engagement };
    return this.outputState;
  }

  private loadTorque(snapshot: VehicleFeedbackSnapshot): number {
    if (snapshot.transmission === undefined || snapshot.transmission.type === 'MANUAL') {
      return finite(snapshot.forces.clutchTorque);
    }
    return finite(snapshot.transmission?.engineLoadTorque, finite(snapshot.forces.clutchTorque));
  }
  private engagement(snapshot: VehicleFeedbackSnapshot): number {
    const dct = snapshot.transmission?.dct;
    return clamp(dct === undefined ? finite(snapshot.clutchEngagement)
      : Math.max(finite(dct.clutchAEngagement), finite(dct.clutchBEngagement)), 0, 1);
  }
}

const finite = (value: number | undefined, fallback = 0): number =>
  value !== undefined && Number.isFinite(value) ? value : fallback;
const smooth = (minimum: number, maximum: number, value: number): number => {
  const fraction = clamp((finite(value) - minimum) / (maximum - minimum), 0, 1);
  return fraction * fraction * (3 - 2 * fraction);
};
const envelope = (current: number, target: number, attack: number, release: number, dt: number): number => {
  const value = damp(current, target, 1 / (target > current ? attack : release), dt);
  return target === 0 && value < 0.0001 ? 0 : value;
};
const emptyState = (): VehicleFeedbackState => ({
  idleVibrationIntensity: 0, clutchJudderIntensity: 0, nearStallVibrationIntensity: 0,
  drivetrainVibrationIntensity: 0, drivetrainJoltIntensity: 0,
  cockpitOffset: { x: 0, y: 0, z: 0 }, continuousRumble: { weak: 0, strong: 0 }, hapticPulses: [],
  factors: { partialClutchFactor: 0, slipFactor: 0, clutchLoad: 0, clutchLoadFactor: 0,
    lowRPMFactor: 0, nearStallFactor: 0, speedAttenuation: 1, autoClutchFeedbackScale: 0,
    judderTarget: 0, nearStallTarget: 0 },
});
